---
permalink: administration/reference_cli_command_for_snap_creator_rbac_actions.html 
sidebar: sidebar 
keywords: snap, creator, rbac, cli, command, user, access 
summary: CLI コマンドを使用して、 Snap Creator の RBAC 操作を実行できます。 
---
= Snap Creator ユーザのアクセス管理に使用するコマンドです
:icons: font
:imagesdir: ../media/


[role="lead"]
CLI コマンドを使用して、 Snap Creator の RBAC 操作を実行できます。

次の表に、 Snap Creator の GUI ベースの RBAC 操作に相当するコマンドラインを示します。

|===
| RBAC エリア | アクション | コマンドおよび関連するパラメータ 


 a| 
ユーザ
 a| 
新しいユーザを作成します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action userAdd
--username user_name
--userPwd user_passwd
--verbose
----


 a| 
ユーザを削除します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action userDelete
--username user_name
--verbose
---- a| 
すべてのユーザをリストします。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action userList
--verbose
---- a| 
特定のロールに割り当てられているすべてのユーザをリストします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action userListAssigned
--roleName role_name
--verbose
----


 a| 
プロファイルが割り当てられているすべてのユーザをリスト表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action userListForProfile
--verbose
---- a| 
ロール



 a| 
新しいロールを作成します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleAdd
--roleName role_name
--roleDesc role_description
--verbose
---- a| 
ロールを削除します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleDelete
--roleName role_name
--verbose
---- a| 
ユーザにロールを割り当てます。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleAssign
--userName user_name
--roleName role_name
--verbose
----


 a| 
ユーザからロールの割り当てを解除します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleUnassign
--userName user_name
--roleName role_name
--verbose
---- a| 
ユーザに割り当てられているロールをすべてリストします。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action roleListAssigned
--userName user_name
--verbose
---- a| 
権限
 a| 
新しい権限を作成します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permAdd
--permName permission_name
--permDesc permission_description
--verbose
---- a| 
権限を削除します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permDelete
--permName permission_name
--verbose
----


 a| 
ユーザに権限を割り当てます。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permAssign
--permName permission_name
--roleName role_name
--verbose
---- a| 
ユーザへの権限の割り当てを解除します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permUnaspermission_namesign
--permName
--roleName role_name
--verbose
---- a| 
すべての権限を一覧表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permList
--verbose
----


 a| 
ロールに割り当てられているすべての権限をリストします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action permListAssigned
--roleName role_name
--verbose
---- a| 
処理



 a| 
権限に処理を割り当てます。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action opAssign
--opName operation_name
--permName permission_name
--verbose
---- a| 
権限から処理の割り当てを解除します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action opUnassign
--opName operation_name
--permName permission_name
--verbose
---- a| 
すべての処理をリスト表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action opList
--verbose
----


 a| 
権限に割り当てられているすべての処理を一覧表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action opListAssigned
--permName permission_name
--verbose
---- a| 
プロファイル



 a| 
ユーザにプロファイルを割り当てます。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileAssign
--userName user_name
--verbose
---- a| 
ユーザーからプロファイルの割り当てを解除します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileUnassign
--userName user_name
--verbose
---- a| 
ユーザに割り当てられているすべてのプロファイルを一覧表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action profileListForUser
--userName user_name
--verbose
----
|===