---
permalink: administration/reference_red_hat_kvm_plug_in.html 
sidebar: sidebar 
keywords: kernel, kvm, virtualization, linux, snap, creator, virsh, command, plug-in, red, hat, guideline 
summary: Kernel-based Virtual Machine （ KVM ）は、 Linux カーネルの仮想化解決策です。Snap Creator は、 KVM プラグインを使用してゲスト仮想マシンのバックアップおよびリストアを行います。 
---
= Red Hat KVM プラグインのガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Kernel-based Virtual Machine （ KVM ）は、 Linux カーネルの仮想化解決策です。Snap Creator は、 KVM プラグインを使用してゲスト仮想マシンのバックアップおよびリストアを行います。


NOTE: サポートと互換性マトリックスに関する最新情報は、 Interoperability Matrix を参照してください。

KVM プラグインは、 Linux 、 Windows 、 Solaris などのゲストオペレーティングシステムをサポートしています。

このプラグインは、 virsh コマンドを内部的に使用します。

KVM プラグインを使用するときは、以下の点を考慮してください。

* プロキシとしての Active IQ Unified Manager サーバはサポートされていません。
* Open Systems SnapVault を使用したマウント、アンマウント、およびバックアップ処理、およびアーカイブログの管理はサポートされていません。
* ストレージエリアネットワーク（ SAN ）環境では、ストレージコントローラから LUN やボリュームに関する情報を収集するために Linux Host Utilities （ LHU ）キットが必要になります。
+
LHU キットは、 Snap Creator エージェントと同じ KVM ハイパーバイザーにインストールされている必要があります。

+

NOTE: LHU キットがインストールされておらず、ネットワーク接続型ストレージ環境とストレージエリアネットワーク環境が混在する構成の場合は、バックアップおよびリストアの操作は NFS 上でのみ機能します。

* KVM プラグインは、 Linux バージョンの Snap Creator 4.0 および 4.1 エージェントのみをサポートしています。
* ボリュームリストアはサポートされません。アプリケーションで定義したリストア処理のみがサポートされます。
* 削除された仮想マシン（ VM ）をリストアすることはできません。
* ストレージコントローラの IP アドレスおよびホスト名は、 KVM ホストの /etc/hosts または Domain Name System （ DNS ；ドメインネームシステム）のいずれかに設定する必要があります。
* 1 つの構成でサポートされる KVM ホストは 1 つだけです。
* ISO リポジトリを使用して仮想マシンが作成されている場合に何らかのアクションを実行するには、 CD-ROM 内のオプションにある Virt Manager コンソールを使用して、このリポジトリの接続を仮想マシンから切断する必要があります。
* SC_AGENT_TIMEOUT には、デフォルト値である 600 以上の値を指定してください。
* ボリュームは自動検出を使用して自動的に検出されます。
+
検出されたデスティネーションボリュームは、デスティネーションが SnapMirror 関係にない場合は表示されません。dpstatus を使用して、 SnapMirror 関係のステータスを確認する必要があります。SnapMirror 関係が存在しない場合は、まず SnapMirror 関係を作成する必要があります。

* APP_DEFINED_RESTORE の値が Y の場合は、 GUI を使用した SnapVault のリストア処理はサポートされません。
* GUI を使用して SnapMirror と SnapVault の構成を作成する場合は、 SnapMirror と SnapVault の関係が自動的に検出されないため、ボリュームの詳細を手動で入力する必要があります。
* VM にマッピングされているデータディスクはバックアップされません。
* VM の一時停止および再開処理は、順次実行されます。
+
複数の VM がある場合、バックアップ処理中に VM が一時停止状態になる時間は、 VM の数によって異なります。





== サポートされる KVM の構成

* SAN ： raw マルチパスデバイス（複数のパスを使用する LUN ）にインストールされているゲスト仮想マシンをサポートします。
* NAS ： NFS ボリュームにインストールされているゲスト仮想マシンをサポートします。



NOTE: 単一のマルチパスデバイスに複数の仮想マシンをインストールした構成はサポートされていません。

SAN 環境で LVM またはイメージファイルにインストールされているゲスト仮想マシンはサポートされません。

次の表に、 KVM プラグインパラメータを示します。

|===
| パラメータ | 設定 | 説明 


 a| 
KVM_RESTORE_VM_LIST
 a| 
例 : VM1 、 VM2
 a| 
リストアする VM のリストを指定します。このパラメータはリストア時にのみ必要です。



 a| 
KVM_VM_MAPPING の略
 a| 
例： `VM1 ： s_c1:/vol/vol1/lun1 ； VM2 ： s_c2 ： /vol/vol2/lun2 ； `
 a| 
（必須） VM とそれに関連付けられたストレージコントローラ、 LUN 、またはファイルパスとの間のマッピングを指定します。このパラメータは、検出処理中に動的に更新されます。



 a| 
KVM_VM_CONFIG_DIR の略
 a| 
デフォルト： /etc/libvirt/qemu
 a| 
（任意） VM のすべての XML 構成ファイルが格納されているディレクトリへのパスを指定します。



 a| 
KVM_CMD_retry_count の略
 a| 
デフォルト値は「 3 」です
 a| 
（オプション） KVM プラグインでコマンドの実行が失敗した場合にコマンドを再実行する回数を指定します。

|===
* 関連情報 *

http://mysupport.netapp.com/matrix["Interoperability Matrix Tool ： mysupport.netapp.com/matrix"]
