---
permalink: administration/reference_snap_creator_framework_error_messages.html 
sidebar: sidebar 
keywords: snap, creator, framework, error, message, troubleshoot, issue, scf, serial, number, plug-in, snapcreator, application 
summary: Snap Creator Framework のエラーメッセージは、発生した問題のトラブルシューティングに役立ちます。 
---
= Snap Creator Framework のエラーメッセージ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Framework のエラーメッセージは、発生した問題のトラブルシューティングに役立ちます。

|===
| エラーコード | エラーメッセージです | 説明 / 解決策 


 a| 
SCF-00001
 a| 
シリアル番号 [%s] を取得できませんでした。
 a| 
Snap Creator setup コマンドは実行されません。snapcreator --profile setup コマンドを実行してください。シリアル番号が空白であるか、数値に設定されていることを確認します。



 a| 
SCF-00002
 a| 
プラグイン [%s] のバックアップ処理がエラー [%s] で失敗し、終了コード [%s] を終了しました。終了します。
 a| 
アプリケーションエラーによりアプリケーションのバックアップに失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00003
 a| 
プラグイン [%s] のバックアップクリーンアップ処理が、エラー [%s] および終了コード [%s] で失敗しました。終了します。
 a| 
アプリケーションエラーにより、アプリケーションバックアップのクリーンアップに失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00004
 a| 
プラグイン [%s] のクローン処理がエラー [%s] で失敗し、終了コード [%s] を終了しました。終了します。
 a| 
アプリケーションエラーによりアプリケーションのクローニングに失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00005
 a| 
プラグイン [%s] のクローンクリーンアップ処理がエラー [%s] で失敗し、終了コード [%s] を終了しました。終了します。
 a| 
アプリケーションエラーによりアプリケーションクローンのクリーンアップに失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00006
 a| 
[%s] のクローン前処理がエラー [%s] で失敗し、終了コード [%s] を終了しました。終了します。
 a| 
アプリケーションエラーによりクローニング前処理に失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00007
 a| 
プラグイン [%s] のクローン後の処理がエラー [%s] で失敗し、終了コード [%s] を終了しました。終了します。
 a| 
アプリケーションエラーによりクローニング後のアプリケーション処理に失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00008
 a| 
[%s] の LUN igroup マッピングを [%s] の igroup [%s] にクローニングできませんでした。終了します。
 a| 
LUN クローンの igroup マッピングに失敗しました。エラーログをチェックしてください。NetApp Manageability SDK 解決策エラーが発生する可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
SCF-00009
 a| 
データセット [%s] の NetApp Management Console バックアップリストの終了に失敗しました。終了コード [%s] があります。終了します。
 a| 
Snap Creator が NetApp Management Console でバックアップの削除処理を開始しましたが、 Snapshot コピーのリストを表示できませんでした。Snap Creator がバックアップを登録していることを確認し、 NTAP_PM_UPDATE パラメータと NTAP_DFM_DATA_SET パラメータの設定をチェックしてください。



 a| 
SCF-00010
 a| 
NetApp Management Console のバックアップリストが定義されていません。データセット [%s] のバックアップは存在しません。終了します。
 a| 
Snap Creator が NetApp Management Console でバックアップの削除処理を開始しましたが、 Snapshot コピーが存在します。Snap Creator がバックアップを登録していることを確認し、 NTAP_PM_UPDATE パラメータと NTAP_DFM_DATA_SET パラメータの設定をチェックしてください。



 a| 
SCF-00011
 a| 
NetApp 管理コンソールのバックアップバージョン ID [%s] のタイムスタンプ [%s] データセット [%s] の削除が、終了コード [%s] で失敗しました。終了します。
 a| 
Snap Creator がバックアップを登録していることを確認し、 NTAP_PM_UPDATE パラメータと NTAP_DFM_DATA_SET パラメータの設定をチェックしてください。



 a| 
SCF-00012
 a| 
データセット [%s] の NetApp Management Console データセットステータスの取得に失敗しました。終了コード [%s] があります。終了します。
 a| 
データセットが存在し、ステータスが Conformant であることを確認します。また、データセットが Snap Creator によって作成されていることも確認します。Snap Creator によって作成されていないデータセットは、アプリケーションデータセットではありません。これらのデータセットは機能しません。



 a| 
SCF-00013
 a| 
Snapshot コピーをデータセット [%s] の終了コード [%s] に登録できませんでした。
 a| 
NTAP_PM_UPDATE パラメータと NTAP_DFM_DATA_SET パラメータの設定をチェックしてください。



 a| 
SCF-00014
 a| 
[%s] （ [%s] ）の NetApp Management Console バックアップの開始に失敗しました。終了します。
 a| 
NTAP_PM_UPDATE パラメータと NTAP_DFM_DATA_SET パラメータの設定をチェックしてください。



 a| 
SCF-00015
 a| 
ジョブ ID [%s] の NetApp Management Console バックアップがエラーで終了しました - [%s]
| [%s] 


| [%s] | [%s]  a| 
Snap Creator が NetApp Management Console のバックアップを開始しましたが、バックアップ処理の進捗状況の取得に失敗しました。NTAP_PM_UPDATE パラメータと NTAP_DFM_DATA_SET パラメータの設定をチェックしてください。



 a| 
SCF-00016
 a| 
[%s] の SnapMirror ステータスが失敗しました。終了します。
 a| 
Snap Creator で、指定されたコントローラの SnapMirror 関係が見つかりませんでした。ストレージコントローラにログインし、 snapmirror status コマンドを実行して、関係が存在することを確認してください。



 a| 
SCF-00017
 a| 
[%s] の SnapMirror 関係： [%s] は存在しません。終了します。
 a| 
Snap Creator で、指定されたコントローラボリュームの SnapMirror 関係が見つかりませんでした。ストレージコントローラにログインし、 snapmirror status コマンドを実行して、特定のコントローラ名の関係が存在することを確認してください。異なる名前を使用している場合は、 SECONDARY INTERFACES パラメータを設定して、ストレージコントローラに何をマッピングするかを Snap Creator で指定する必要があります。



 a| 
SCF-00018
 a| 
[%s] の SnapVault ステータスリストが失敗しました。終了します。
 a| 
Snap Creator で、指定されたコントローラの SnapVault 関係が見つかりませんでした。ストレージコントローラにログインし、 SnapVault status コマンドを実行してください。SnapVault 関係が存在することを確認してください。



 a| 
SCF-00019
 a| 
[%s] の SnapVault 関係： [%s] は存在しません。終了します。
 a| 
Snap Creator で SnapVault 関係が見つかりませんでした。ストレージコントローラにログインして、 SnapVault status コマンドを実行してください。指定したコントローラ名の SnapVault 関係が存在することを確認してください。異なる名前を使用している場合は、 SECONDARY_INTERFACES パラメータを設定して、ストレージコントローラに何をマッピングするかを Snap Creator で指定する必要があります。



 a| 
SCF-00020
 a| 
デスティネーション [%s] でソース [%s] を使用した SnapVault 更新の実行に失敗しました。
 a| 
Snap Creator は SnapVault の更新を開始できませんでした。ストレージコントローラにログインし、 SnapVault status コマンドを実行します。指定したコントローラ名の SnapVault 関係が存在することを確認してください。異なる名前を使用している場合は、 SECONDARY_INTERFACES パラメータを設定して、ストレージコントローラに何をマッピングするかを Snap Creator で指定する必要があります。



 a| 
SCF-00021
 a| 
SnapMirror 転送エラーが検出されました - [%s] 、終了します。
 a| 
エラーおよび SnapMirror のストレージコントローラ設定をチェックします。



 a| 
SCF-00022
 a| 
ソース [%s] での SnapMirror 更新を [%s] 分以内に完了できませんでした。終了します。
 a| 
SnapMirror の更新に、設定されている待機時間より長い時間がかかりました。構成ファイルの NTAP_SNAPMIRROR_WAIT の値を増やすことで、待機時間を調整できます。



 a| 
SCF-00023
 a| 
ソース [%s] での SnapVault 更新は [%s] 分後に完了できませんでした。終了します。
 a| 
SnapVault の更新に、設定されている待機時間より長い時間がかかりました。構成ファイルの NTAP_SNAPVAULT_WAIT の値を増やすことで、待機時間を調整できます。



 a| 
SCF-00024
 a| 
SnapVault 転送エラーが検出されました - [%s] 、終了します。
 a| 
エラーおよび SnapVault のストレージコントローラ設定を確認します。



 a| 
SCF-00025
 a| 
プラグイン [%s] のリストア後の処理がエラー [%s] および終了コード [%s] で失敗しました。
 a| 
アプリケーションエラーにより、アプリケーションのリストア後の処理に失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00026
 a| 
プラグイン [%s] のリストアクリーンアップ処理がエラー [%s] で失敗しました。終了コード [%s]
 a| 
アプリケーションエラーにより、アプリケーションのリストアクリーンアップ処理に失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00027
 a| 
プラグイン [%s] のリストア前処理がエラー [%s] および終了コード [%s] で失敗しました。
 a| 
アプリケーションエラーにより、アプリケーションのリストア前の処理に失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00028
 a| 
プラグイン [%s] の自動検出に失敗しました。エラー [%s] 、終了コード [%s] 、終了します。
 a| 
アプリケーションエラーによりアプリケーション検出に失敗しました。ログとアプリケーション設定を確認してください。また、自動検出は APP_AUTO_DISCOVERY = N に設定し VALIDATE_VOLUMES をコメントアウトすることで無効に設定できます。



 a| 
SCF-00029
 a| 
環境が空のため、プラグイン [%s] の自動検出に失敗しました。終了します。
 a| 
アプリケーションプラグインは、自動検出の使用をサポートしていません。APP_AUTO_DISCOVERY = N に設定し、自動検出を無効に設定してください



 a| 
SCF-00030
 a| 
プラグイン [%s] のファイルシステムの休止に失敗しました。エラー [%s] 、終了コード [%s] 、終了します。
 a| 
ファイルシステムエラーにより、ファイルシステムの休止に失敗しました。ログとファイルシステムの設定を確認してください。エラーを無視しバックアップを続行するには、 APP_IGNORE_ERROR=Y に設定します



 a| 
SCF-00031
 a| 
プラグイン [%s] のファイルシステム休止中にエラーが発生しました。終了コード [%s] を終了し、バックアップを続行しています。
 a| 
ファイルシステムエラーにより、ファイルシステムの休止に失敗しました。ただし、 APP_IGNORE_ERROR=Y と設定されています。 Snap Creator はバックアップを続行します。ログとファイルシステムの設定を確認してください。



 a| 
SCF-00032
 a| 
アプリケーションエラーによりアプリケーション休止解除に失敗しました。アプリケーションエラーを無視しバックアップを続行するには、 APP_IGNORE_ERROR=Y に設定します
 a| 
ログとアプリケーション設定を確認してください。



 a| 
SCF-00033
 a| 
プラグイン [%s] のアプリケーション休止解除に終了コード [%s] が失敗しました。バックアップを続行しています。
 a| 
アプリケーションエラーにより、アプリケーションの休止解除に失敗しました。ただし、 APP_IGNORE_ERROR=Y と設定されており、 Snap Creator はバックアップを続行します。ログとアプリケーション設定を確認してください。



 a| 
SCF-00034
 a| 
[%s] （ [%s] ）から [%s] （ [%s] ）への LUN クローンの作成に失敗しました。終了します。
 a| 
LUN クローンの作成に失敗しました。エラーログをチェックしてください。NetApp Manageability エラーが発生する可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
SCF-00035
 a| 
[%s] の LUN のインベントリに失敗しました。終了します。
 a| 
LUN リストの作成に失敗しました。エラーログをチェックしてください。NetApp Manageability エラーが発生する可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
SCF-00036
 a| 
プラグイン [%s] のアプリケーション休止に失敗しました。プラグインから終了コードが返されませんでした。終了します。
 a| 
アプリケーションの休止が終了コードなしで終了しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00037
 a| 
プラグイン [%s] のアプリケーション休止に失敗しました。エラー [%s] 、終了コード [%s] 、終了します。
 a| 
アプリケーションエラーによりアプリケーションの休止に失敗しました。ログとアプリケーション設定を確認してください。アプリケーションエラーを無視しバックアップを続行するには、 APP_IGNORE_ERROR=Y に設定します



 a| 
SCF-00038
 a| 
プラグイン [%s] のアプリケーション休止に終了コード [%s] が失敗しました。バックアップを続行しています。
 a| 
アプリケーションエラーによりアプリケーションの休止に失敗しました。ただし、 APP_IGNORE_ERROR=Y と設定されており、 Snap Creator はバックアップを続行します。ログとアプリケーション設定を確認してください。



 a| 
SCF-00039
 a| 
指定したコントローラ [%s] が構成に指定されたコントローラと一致しませんでした。構成ファイルで NTAP_USERS パラメータをチェックしてください。
 a| 
NTAP_USERS をチェックし、構成ファイルにストレージコントローラが定義されていることを確認してください。



 a| 
SCF-00040
 a| 
指定したボリューム [%s] が、設定で指定されたストレージシステムまたはボリュームと一致しませんでした。構成ファイルで VOLUMES パラメータをチェックしてください。
 a| 
構成ファイルで VOLUMES の設定をチェックし、正しいコントローラボリュームが設定されていることを確認します。



 a| 
SCF-00041
 a| 
clustered Data ONTAP が検出されましたが、 CMODE_CLUSTER_NAME が正しく設定されていません。設定パラメータを確認して終了します。
 a| 
AutoSupport と SnapMirror には、 CMODE_CLUSTER_NAME パラメータを使用する必要があります。このパラメータは構成ファイルで正しく定義する必要があります。



 a| 
SCF-00042
 a| 
clustered Data ONTAP が検出されましたが、 CMODE_CLUSTER_USERS が正しく設定されていません。設定パラメータを確認して終了します。
 a| 
AutoSupport と SnapMirror には、パラメータ CMODE_CLUSTER_NAME および CMODE_CLUSTER_USERS を使用する必要があります。これらのパラメータは構成ファイルで正しく定義する必要があります。



 a| 
SCF-00043
 a| 
clustered Data ONTAP では SnapVault はサポートされません。構成で NTAP_SNAPVAULT_UPDATE を N に設定します。
 a| 
構成を確認し、パラメータを変更してください。clustered Data ONTAP は SnapVault をサポートしていません。



 a| 
SCF-00044
 a| 
META_DATA_VOLUME パラメータは定義されますが、ストレージシステム：指定されたボリュームは VOLUMES パラメータで設定されている内容と一致しません。構成を確認します。
 a| 
META_DATA_VOLUME パラメータは、ボリュームには指定されていません。ボリュームにメタデータボリュームを追加します。



 a| 
SCF-00045
 a| 
META_DATA_VOLUME パラメータは定義されますが、 VOLUMES パラメータで指定されている唯一のボリュームにすることはできません。メタデータボリュームは別のボリュームである必要があります。
 a| 
META_DATA_VOLUME に指定されたボリュームは、 VOLUMES に存在する唯一のボリュームです。他のボリュームも存在する必要があります。META_DATA_VOLUME は、通常の Snapshot 処理には使用しないでください。



 a| 
SCF-00046
 a| 
NetApp Management Console では、タイムスタンプ Snapshot コピーのみがサポートされます。
 a| 
構成ファイルを更新し、 SNAP_TIMESTAMP_ONLY オプションを Y に設定します



 a| 
SCF-00047
 a| 
互換性のない設定が選択されています。NTAP_SNAPVAULT_UPDATE オプションと NTAP_SNAPVAULT_SNAPSHOT オプションの両方を有効にすることはできません
 a| 
構成ファイルを編集し、 2 つのオプションのいずれかを無効にします。



 a| 
SCF-00048
 a| 
プラグイン [%s] のマウント処理がエラー [%s] で失敗し、終了コード [%s] を終了しました。終了します。
 a| 
アプリケーションエラーによりアプリケーションのマウントに失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00049
 a| 
プラグイン [%s] のアンマウント処理がエラー [%s] で失敗し、終了コード [%s] を終了しました。終了します。
 a| 
アプリケーションエラーによりアプリケーションのアンマウントに失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00050
 a| 
カスタムアクションはアプリケーションプラグインでのみサポートされます
 a| 
構成ファイルに APP_NAME パラメータが設定されていません。このパラメータは、使用するプラグインを決定します。カスタムアクションは、アプリケーションプラグインでのみサポートされます。



 a| 
SCF-00051
 a| 
[%s] の NetApp Management Console データセットの作成に失敗しました。終了コードは [%s] です。終了します。
 a| 
デバッグエラーメッセージを確認します。Active IQ Unified Manager サーバとの通信中に問題が発生する可能性があります。



 a| 
SCF-00052
 a| 
プラグイン [%s] のリストア処理がエラー [%s] 終了コード [%s] で失敗しました。終了します。
 a| 
アプリケーションエラーによりリストアに失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00053
 a| 
プラグイン [%s] のファイルシステムの休止解除に失敗しました。エラー [%s] 、終了コード [%s] 、終了します。
 a| 
ファイルシステムエラーにより、ファイルシステムの休止解除に失敗しました。ただし、 APP_IGNORE_ERROR=Y と設定されており、 Snap Creator はバックアップを続行します。ログとファイルシステムの設定を確認してください。



 a| 
SCF-00054
 a| 
プラグイン [%s] のファイルシステムの休止解除でエラーが発生しました。終了コード [%s] を終了し、バックアップを続行しています。
 a| 
ファイルシステムエラーにより、ファイルシステムの休止解除に失敗しました。ただし、 APP_IGNORE_ERROR=Y と設定されており、 Snap Creator はバックアップを続行します。ログとファイルシステムの設定を確認してください。



 a| 
SCF-00055
 a| 
NetApp Management Console がバックアップ [%s] （データセット [%s] ）をストレージコントローラ [%s] でポリシー [%s] で駆動しました。
 a| 
該当なし



 a| 
SCF-00056
 a| 
データセット [%s] の NetApp Management Console ベースのバックアップ [%s] をストレージコントローラ [%s] にポリシー [%s] で作成しました
 a| 
該当なし



 a| 
SCF-00057
 a| 
データセット [%s] の NetApp Management Console ベースのバックアップ [%s] をストレージコントローラ [%s] でポリシー [%s] で作成できませんでした。エラー [%s] が発生しました。
 a| 
NTAP_PM_UPDATE パラメータと NTAP_DFM_DATA_SET パラメータの設定をチェックしてください。



 a| 
SCF-00058
 a| 
アプリケーションで検出された値を使用して設定を更新できませんでした。 [%s] 、終了します。
 a| 
権限の問題またはアプリケーションから返された値を解析できなかったため、ファイルを更新できませんでした。Snap Creator を実行しているユーザの権限をチェックし、その権限が正しいことを確認してください。



 a| 
SCF-00059
 a| 
[%s] プラグイン [%s] のダンプが終了コード [%s] で失敗しました。終了します。
 a| 
アプリケーションエラーにより、 scdump アクションに失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00060
 a| 
無効な DTO ： [%s]
 a| 
DTO の必須フィールドが設定されていないか無効です。これが原因で DTO の処理時に検証エラーが発生しました。問題を修正して、 DTO を再送信してください。



 a| 
SCF-00061
 a| 
アーカイブログの削除に失敗しました。エラー [%s] が発生しました。終了します。
 a| 
Snap Creator はアプリケーションのアーカイブログを削除できませんでした。Snap Creator ユーザの権限をチェックしてください。構成に応じて、 Snap Creator サーバまたは Snap Creator エージェントであることが必要です。



 a| 
SCF-00062
 a| 
認証に失敗しました。
 a| 
ユーザに処理を実行する権限がないため、認証に失敗しました。



 a| 
SCF-00063
 a| 
[%s] の検出に失敗しました。戻りコード [%s] とメッセージ [%s] があります。
 a| 
アプリケーションエラーにより、 VALIDATE_VOLUMES=DATA を使用するアプリケーション検出に失敗しました。ログとアプリケーション設定を確認してください。



 a| 
SCF-00064
 a| 
検出でストレージオブジェクトが検出されませんでした
 a| 
VALIDATE_VOLUMES=DATA を使用するアプリケーション検出に失敗しました。Snap Creator は、ストレージシステムにあるデータボリュームを検出できませんでした。自動検出を無効にするには、 VALIDATE_VOLUMES をコメントアウトします。



 a| 
SCF-00065
 a| 
ボリューム [%s] （ [%s] 、 [%s] ）は構成ファイルに含まれていません
 a| 
アプリケーション検出により、一部のボリュームがないことが検出されました。欠落しているボリュームがバックアップに含まれるように、それらのボリュームを VOLUMES パラメータに追加します。



 a| 
SCF-00066
 a| 
[%s] のエージェント検証に失敗しました。エラー [%s]
 a| 
設定されたエージェントにアクセスできません。エージェントが停止しているか、ローカルファイアウォールの問題が存在する可能性があります。構成パラメータ SC_AGENT をチェックしてください。



 a| 
SCF-00067
 a| 
[%s] の外部 Snapshot コピーを名前パターン [%s] でリストできませんでした。
 a| 
Snap Creator は、正規表現パターン NTAP_EXTERNAL_SNAPSHOT_REGEX に基づいて外部の Snapshot コピーを検出できませんでした。コントローラにログインし、 snap list の出力と regex パターンを照合します。



 a| 
SCF-00068
 a| 
プラグイン [%s] のファイルシステム Pre_restore が終了コード [%s] で失敗しました。終了します。
 a| 
ファイルシステムエラーにより、ファイルシステムのリストア前の処理に失敗しました。ログとファイルシステムの設定を確認してください。



 a| 
SCF-00069
 a| 
プラグイン [%s] のファイルシステム Pre_restore でエラー終了コード [%s] が発生しました。バックアップを続行しています。
 a| 
ファイルシステムエラーにより、ファイルシステムのリストア前の処理に失敗しました。ただし、 APP_IGNORE_ERROR=Y と設定されており、 Snap Creator は他の処理を続行します。ログとファイルシステムの設定を確認してください。



 a| 
SCF-00070
 a| 
プラグイン [%s] のファイルシステム post_restore が終了コード [%s] で失敗しました。終了します。
 a| 
ファイルシステムエラーにより、ファイルシステムのリストア後の処理に失敗しました。ログとファイルシステムの設定を確認してください。



 a| 
SCF-00071
 a| 
プラグイン [%s] のファイルシステム post_restore でエラーが発生しました。終了コード [%s] を終了し、バックアップを続行しています。
 a| 
ファイルシステムエラーにより、ファイルシステムのリストア後の処理に失敗しました。ただし、 APP_IGNORE_ERROR=Y と設定されており、 Snap Creator は他の処理を続行します。ログとファイルシステムの設定を確認してください。



 a| 
SCF-00072
 a| 
ポリシー [%s] は、設定内で定義されている Snapshot コピー保持ポリシーではありません。終了します。
 a| 
使用しているポリシーが無効です。構成ファイルをチェックし、 NTAP_SNAPSHOT_RETENTIONS が適切に設定されます。

|===