---
permalink: administration/reference_snap_creator_agent_error_messages.html 
sidebar: sidebar 
keywords: snap, creator, agent, error, message, aft, sc_agentconfiguration, parameter, remote, port 
summary: 次の表に、 Snap Creator エージェントのエラーメッセージを示します。 
---
= Snap Creator エージェントのエラーメッセージ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、 Snap Creator エージェントのエラーメッセージを示します。

|===
| エラーコード | 説明 / 解決策 


 a| 
AGT-00001
 a| 
Snap Creator エージェントまたはその他のプロセスが、指定されたポートで実行しています。別のポートを使用してください。



 a| 
AGT-00003
 a| 
指定したパラメータは、 Snap Creator エージェントを起動するために正しくありませんでした。必要なパラメータを確認します。



 a| 
AGT-00004
 a| 
リモートエージェントを使用する場合は、 SC_AGENT 構成パラメータを定義する必要があります。



 a| 
AGT-00005
 a| 
休止処理を連続して実行することはできません。すでに休止が実行中です。待機するか休止解除を実行します。



 a| 
AGT-00006
 a| 
watchdog プロセスが起動できません。システムのプロセス数が最大数に達している可能性があります。構成ファイルで watchdog を無効に設定するか、またはオペレーティングシステムの設定をチェックしてください。



 a| 
AGT-00008
 a| 
休止および休止解除の処理が完了せず、バックアップは crash-consistent のみとなります。ログをチェックしてください。このエラーは、休止処理に時間がかかり、 watchdog を使用している場合に発生することがあります。watchdog プロセスは、構成ファイルで定義される x 秒後に休止解除を強制的に実行します。



 a| 
AGT-00009
 a| 
エージェント側の agent.conf で PRE および POST のコマンドが許可されている必要があります。agent.conf を更新し ' 必要なコマンドを許可します



 a| 
AGT-00010
 a| 
エージェントは構成ファイルを読み取ることができませんでした。agent.conf ファイルに対する権限をチェックしてください。



 a| 
AGT-00011
 a| 
コマンドがエージェントに送信されましたが、許可されていません。コマンドを許可するには、 agent.conf を更新します。



 a| 
AGT-00012
 a| 
このエラーはプラグインのロード中に発生します。プラグインと APP_NAME の設定をチェックしてください。



 a| 
AGT-00013
 a| 
このエラーは、プラグイン内で setenv メソッドの実行中に発生します。プラグインをチェックし、構文が正しいことを確認してください。

|===