---
permalink: administration/reference_troubleshooting_network_issues.html 
sidebar: sidebar 
keywords: network, issues, snap, creator, authorization, failure, troubleshoot, nat 
summary: Snap Creator で、認証エラーなどのネットワークの問題が発生する可能性があります。これらの問題について理解し、トラブルシューティングの方法を把握しておく必要があります。 
---
= ネットワークの問題のトラブルシューティング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator で、認証エラーなどのネットワークの問題が発生する可能性があります。これらの問題について理解し、トラブルシューティングの方法を把握しておく必要があります。

* * 問題 *
+
Snap Creator 内で認証エラーの問題が発生する。

* * 原因 *
+
認証エラーの原因には、設定、ファイアウォールの権限、または Network Address Translation （ NAT; ネットワークアドレス変換）などがあります。

* * 是正措置 *
+
次の点を確認します。

+
** IP/Host 名
+
host equiv を使用する場合を除き、コントローラ上で hostname コマンドを実行した際に返されるストレージシステム名は、 Snap Creator の構成ファイルで指定した名前と同一である必要があります。

+
ストレージシステムのホスト名が短縮されている場合は、 Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）を使用しないでください。

+
IP の解決方法が指定した名前と一致することを確認します。不一致がある場合は、ストレージ・システムの host equiv を使用して修正します。

+
host equiv を有効化するには、次の手順を実行します。

+
... 次のコマンドを入力します。 options https.admin.hostsequiv.enable on
... /etc/hostsequiv のファイルを編集し、次を追加します。 IP/Host_name_in_SnapCreator config_fileSnapCreator _Creator_user


** NetApp Management Console のデータ保護機能
+
Snap Creator の構成パラメータ VOLUMES に定義されているストレージコントローラの名前は、 NetApp Management Console のデータ保護機能のストレージコントローラの名前と一致する必要があります。ストレージコントローラの名前が一致しない場合は、オペレーティングシステムのホストファイルを使用して、ストレージコントローラの名前を強制的に一致させることができます。

** ファイアウォール：
+
Snap Creator を実行するホストとストレージシステムの間にファイアウォールがある場合には、双方向の Access Control List （ ACL ；アクセス制御リスト）を用意し、ポートの 80 と 443 のいずれか、または両方をオープンにする必要があります。

+
*** 80 ： HTTP が選択されている場合に、ストレージシステムとの通信に使用されます
*** 443 ： Linux 、 Solaris 、 AIX のいずれかで HTTPS （ 443 ）を使用するように HTTPS を選択した場合にストレージシステムとの通信に使用するために、 SSL を使用するために必要な openssl ライブラリをインストールします。




+
Snap Creator エージェントが実行されている場合は、エージェントが実行されているポートがオープンである必要があります。少なくとも非特権ポートでは、ストレージシステムからのリターントラフィックが、 Snap Creator を実行しているシステムに確実に到達できるようにします。

+
** Snap Creator Framework は、 SSL が無効な場合、 TLS を使用して 7-Mode の clustered Data ONTAP と Data ONTAP の両方と通信できます。
+
Snap Creator Framework では、ホストとストレージシステムの SSLv3 を無効にすることができます。

+
*** AIX 、 UNIX 、または Windows で SSLv3 を無効にするには、 java.security ファイルで JDK.tls.disableAlgorithms パラメータを次のように更新します。
+
JDK.tls.disableAlgorithms = SSLv3

+
java.security ファイルは、 /java/jre/lib/security/ というパスにあります

*** ストレージシステムで SSLv3 を無効にするには、 system service web modify コマンドを実行し、次のパラメータを設定します。
+
TLSv1 が有効： true

+
SSLv3 が有効： false

+
SSLv2 が有効になっている： false



** NAT
+
NAT を使用する場合は、送信元 / 宛先 IP アドレスが Transmission Control Protocol （ TCP ）パケット内で変更されていないことを確認します。ホストおよびストレージシステムは、通信相手を認識する必要があります。実際のホストやコントローラの IP アドレスではなくファイアウォールの IP アドレスを指定すると、原因で問題が発生する可能性があります。




