---
permalink: administration/reference_snap_creator_terminology.html 
sidebar: sidebar 
keywords: snap, creator, terminology,action, backup, lun, clone, volume, agent, monitor, archive, log, configuration, discover, global, job, mount, ossv, profile, policy, quiesce, restore, scdump, schedule, umount, unquiesce, watchdog 
summary: Snap Creator はいくつかの異なる構成要素で構成されており、言語と概念を理解することが重要です。 
---
= Snap Creator の用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator はいくつかの異なる構成要素で構成されており、言語と概念を理解することが重要です。

* * アクション *
+
Snap Creator は構成ファイルに対してさまざまな操作を実行できます。これは通常、望ましい結果を得るための定義済みワークフローです。アクションを実行するには、 GUI から構成ファイルを選択し、 * アクション * をクリックして、ドロップダウンリストから次のいずれかのアクションを選択します。

+
** * バックアップ *
+
構成ファイルで指定された環境をバックアップします。バックアップワークフローは、選択した構成ファイルの設定に応じて複数の手順で変更するアクションです。プラグインが設定されたバックアップ処理の例としては、アプリケーションまたはデータベースの休止、定義されたすべてのボリュームの Snapshot コピーの作成、選択されたアプリケーションまたはデータベースの休止解除、 SnapVault または SnapMirror 更新の実行、保持ポリシーへの対応、アーカイブログの設定への対応などがあります。

** * lun clone *
+
LUN の新しい Snapshot コピーを作成し、そのクローンを作成します。

** * ボリュームクローン *
+
ボリュームの新しい Snapshot コピーを作成し、そのクローンを作成します。



* * エージェントモニター *
+
Agent Monitor は、構成ファイルに定義されているすべてのエージェントを Snap Creator サーバに照会し、エージェントにステータスの確認を照会します。エージェントモニタは、エージェントが稼働しているかどうか、エージェントが待機しているポート、およびエージェントのバージョンが使用中であるかどうかを報告します。

* * ログをアーカイブ *
+
アーカイブログアクションは、構成ファイルのアーカイブログ管理設定の任意の設定に対して動作します。通常、この処理を実行すると、 Snap Creator で不要になったログがパージされます。

* * 設定ファイル *
+
Snap Creator の中核をなすのが、構成ファイルです。Snap Creator を構成し、アプリケーションプラグインの実行を可能にし、必要な変数を設定し、 Snapshot コピーにキャプチャされるボリュームを定義します。構成ファイルはさまざまなパラメータで構成され、 Snap Creator の動作に影響するように設定できます。構成ファイルは、多くの場合、構成ファイルまたは構成ファイルに短縮されます。

* * 発見 *
+
検出処理を実行すると、構成ファイルに詳細に記述されている環境でストレージレベルの検出が実行されます。すべてのプラグインが検出をサポートしているわけではありません

* * グローバル構成ファイル *
+
スーパーグローバルレベル（パラメータが Snap Creator サーバ環境全体のすべての構成ファイルに影響）またはプロファイルレベル（パラメータは指定されたプロファイル内のすべての構成ファイルに影響）のいずれかで動作可能な構成ファイル。スーパーグローバルパラメータは、プロファイルレベルのグローバルで指定されたパラメータで上書きされます。同様に、構成ファイルで指定されたパラメータは、スーパーレベルまたはプロファイルレベルのグローバル構成ファイル内のパラメータよりも優先されます。グローバル構成ファイルは、多くの場合、グローバル構成に短縮されます。

* * ジョブ *
+
Snap Creator によって実行されるすべての処理がジョブとみなされます。一部の操作は複数のジョブで構成される場合があります。Snap Creator によって実行されたすべてのジョブは、ジョブモニタに表示されます。

* * ジョブモニタ *
+
ジョブモニタは、実行中または以前に実行された Snap Creator ジョブのステータスを簡単に確認できる使いやすいダッシュボードインターフェイスです。ジョブモニタはセットアップ時に有効になり、 1 ～ 1,000 のジョブを保存できます。

* * マウント *
+
マウント操作では、クローニングおよびマウントされる既存の Snapshot コピーを指定できます。

* * OSSV *
+
OSSV （ Open Systems SnapVault ）アクションは、 OSSV 処理を実行します。

* * プロファイル *
+
プロファイルは、基本的には構成ファイルの整理に使用されるフォルダです。また、プロファイルはロールベースアクセス制御（ RBAC ）のオブジェクトとしても機能します。つまり、ユーザがアクセスできるのは、特定のプロファイルと構成ファイルに限られます。

* * ポリシー *
+
ポリシーは保持ポリシーに対しては省略されています。通常、ポリシーでは Snapshot 保持ポリシー（保持する Snapshot コピーの数）と保持期間（ Snapshot コピーを削除するまでの経過時間）を定義します。たとえば、日単位のポリシーでは、 30 日分以上前の Snapshot コピーを 30 日間保持することができます。（保持期間を設定すると、同じ日に作成された複数の Snapshot コピーの SLA が回避されます。 SLA の規定によっては、 Snapshot コピーの保持期間を 30 日に設定する必要があります） SnapVault を使用する場合は、 SnapVault コピーの保持設定もポリシーで定義されます。現在、ポリシーは、直接構成ファイルに格納することも、ポリシーオブジェクトの一部として格納することもできます。ポリシーが構成ファイルに含まれている場合は、ローカル保持ポリシーと呼ばれます。

* * ポリシーオブジェクト *
+
ポリシーオブジェクトは、プロファイルレベルで適用できる保持ポリシーです。ポリシーと同様に、ポリシーオブジェクトでも保持ポリシーが定義されますが、スケジュールとラベルを定義することもできます。ポリシーオブジェクトのコンポーネントは次のとおりです。

+
** * バックアップタイプ *
+
バックアップタイプは、ポリシーオブジェクトで設定できるラベルです。

** * ポリシーの割り当て *
+
ポリシー割り当てでは、ポリシー（ポリシー管理で作成）を特定のプロファイルに割り当てます。

** * ポリシー管理 *
+
ポリシー管理によって、ポリシーオブジェクト内にポリシーが作成されます。これにより、 Snapshot コピーの保持数と保持期間を定義できます。SnapVault を使用する場合は、関連付けられている保持数と保持期間も設定できます。ポリシー管理では、オプションでポリシースケジュールとバックアップタイプを選択することもできます。

** * ポリシースケジュール *
+
ポリシースケジュールでは、指定したスケジュールで実行する処理を定義します。



* * 休止 *
+
休止アクションは、アプリケーションまたはデータベースを整合性のある状態にするために必要なアクションを実行します。quiesce という名前の処理はありますが、プラグインまたは構成ファイルの設定によっては、 true 静止処理でない場合があります。たとえば、 Domino プラグインは Domino API 呼び出しを実行して Domino データベースをバックアップの開始状態にしますが、 DB2 プラグインは db2 write suspend コマンドを実行します。

* * 復元 *
+
リストア処理では、構成ファイルで指定された 1 つ以上のボリュームに対してボリュームまたは単一ファイルのリストア処理が実行されます。構成ファイルで使用しているプラグインによっては、追加のリストア処理を実行できる場合があります。

* * scdump *
+
scdump は、すべての構成ファイルとログファイルをプロファイルレベルで収集し、 Snap Creator サーバの標準的なログと環境情報を収集するトラブルシューティング処理です。収集されたこれらのファイルはすべて zip ファイルに圧縮され、ダウンロードするように求められます。その後、 scdump zip ファイルを E メールで送信、またはサポートにアップロードして分析を行うことができます。

* * スケジュール *
+
Snap Creator サーバには一元化されたスケジューラがあります。これにより、 Snap Creator ジョブのスケジュールをポリシースケジュール（ポリシーオブジェクトの一部）を使用して設定するか、スケジューラを通じて直接作成することができます。スケジューラは最大 10 個のジョブを同時に実行し、実行中のジョブが完了するまで追加のジョブをキューに登録します。

* * Snap Creator エージェント *
+
通常、 Snap Creator エージェントは、アプリケーションまたはデータベースのインストール先と同じホストにインストールします。Agent は、プラグインが配置されている場所です。Snap Creator 内でエージェントが scAgent に短縮されることがあります。

* * Snap Creator Framework *
+
Snap Creator はフレームワークであり、製品名はすべて NetApp Snap Creator Framework です。

* * Snap Creator プラグイン *
+
プラグインを使用すると、アプリケーションやデータベースを整合性のある状態にすることができます。Snap Creator には、すでにバイナリファイルに含まれているプラグインがいくつか含まれているため、追加のインストールは必要ありません。

* * Snap Creator サーバ *
+
Snap Creator サーバは、通常、物理ホストまたは仮想ホストにインストールします。サーバは、 Snap Creator の GUI 、およびジョブ、スケジュール、ユーザ、ロール、プロファイルに関する情報の格納に必要なデータベースをホストし、 構成ファイル、およびプラグインのメタデータ。Snap Creator 内ではサーバが scServerに 短縮されることがあります。

* * アンマウント *
+
umount アクションを使用すると、アンマウントする既存のマウントポイントを指定できます。

* * 休止解除 *
+
休止解除処理は、アプリケーションまたはデータベースを通常の動作モードに戻すために必要な処理を実行します。この処理は休止解除と呼ばれますが、プラグインまたは構成ファイルの設定によっては、休止解除が true にならない場合があります。たとえば、 Domino プラグインは Domino API 呼び出しを実行して Domino データベースをバックアップの停止状態にし、 DB2 プラグインは write resume コマンドを実行します。

* * ウォッチドッグ *
+
watchdog は Snap Creator エージェントの一部であり、エージェントが実行しているジョブのステータスを監視します。指定された時間内にエージェントが応答しない場合、ウォッチドッグはエージェントを再起動するか、特定のアクションを終了します。たとえば、休止処理がタイムアウト値を超えると、 watchdog は休止アクションを停止し、休止解除を開始してデータベースを通常の動作モードに戻すことができます。


