---
permalink: administration/reference_repository_error_messages.html 
sidebar: sidebar 
keywords: table, repository, error, message, global, configuration, repo 
summary: 次の表に、リポジトリのエラーメッセージを示します。 
---
= リポジトリエラーメッセージ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、リポジトリのエラーメッセージを示します。

|===
| エラーコード | エラーメッセージです | 説明 / 解決策 


 a| 
rep2-01001
 a| 
グローバル構成が存在しません
 a| 
global.conf ファイルが configs フォルダにあるかチェックします。



 a| 
rep2-01002
 a| 
グローバル設定はすでに存在します
 a| 
global.conf ファイルは configs フォルダにすでに存在します。最初にグローバル構成ファイルを削除するか、既存のファイルを更新してください。



 a| 
（ 2004 年 11 月現在／ repo
 a| 
グローバル設定の作成に失敗しました。エラー [%s]
 a| 
configs フォルダに global.conf ファイルを作成できませんでした。Snap Creator を実行しているユーザのディレクトリに対する権限をチェックしてください。



 a| 
repo -01203.
 a| 
グローバル設定の更新に失敗しました。エラー [%s] が発生しました。
 a| 
configs フォルダの global.conf ファイルを更新できませんでした。Snap Creator を実行しているユーザのディレクトリに対する権限をチェックしてください。



 a| 
repo -01303.
 a| 
グローバル設定を削除できませんでした。エラー [%s] が発生しました。
 a| 
configs フォルダ内の global.conf ファイルを削除できませんでした。このファイルが configs フォルダにあるか、または Snap Creator を実行しているユーザのディレクトリに対する権限をチェックします



 a| 
repo -01403.
 a| 
グローバル設定のエクスポートに失敗しました。エラー [%s] が発生しました。
 a| 
configs フォルダの global.conf ファイルを読み取れませんでした。グローバル構成ファイルが削除されているかどうかを確認します。



 a| 
repo -01503
 a| 
グローバル構成 [%s] のインポートに失敗しました。エラー [%s]
 a| 
configs フォルダの global.conf ファイルを更新できませんでした。Snap Creator を実行しているユーザのディレクトリに対する権限をチェックしてください。



 a| 
repo -01603
 a| 
グローバル設定を取得できませんでした。エラー [%s] が発生しました。
 a| 
configs フォルダの global.conf ファイルを読み取れませんでした。グローバル構成ファイルが削除されているかどうかを確認します。



 a| 
（ 2002 年 2 月現在／ repo
 a| 
プロファイル [%s] はすでに存在します。別の名前を使用してください。
 a| 
同じ名前のプロファイルがすでに存在します。プロファイルが表示されない場合、ユーザにはこのプロファイルに対する権限がありません。



 a| 
repo -02003
 a| 
プロファイル [%s] は存在しません
 a| 
プロファイルの名前が変更されていないか、削除されていないかまた、ユーザにこのプロファイルに対する権限がない可能性があります。



 a| 
repo_02103 が表示されます
 a| 
グローバルプロファイル設定 [%s] の作成に失敗しました。エラー [%s]
 a| 
プロファイルに global.conf ファイルを作成できませんでした。Snap Creator を実行しているユーザのディレクトリに対する権限をチェックしてください。



 a| 
rep02106
 a| 
プロファイル設定 [%s] の作成に失敗しました。エラー [%s]
 a| 
configs フォルダにプロファイルを作成できませんでした。Snap Creator を実行しているユーザのディレクトリに対する権限をチェックしてください。



 a| 
rep2-02203
 a| 
プロファイル設定 [%s] の更新に失敗しました。エラー [%s]
 a| 
configs フォルダ内のプロファイルを更新できませんでした。Snap Creator を実行しているユーザのディレクトリに対する権限をチェックしてください。



 a| 
repo_2213
 a| 
プロファイル [%s] の [%s] への名前変更がエラー [%s] で失敗しました。
 a| 
configs フォルダにあるプロファイルの名前を変更できませんでした。Snap Creator を実行しているユーザのディレクトリに対する権限をチェックするか、すでにプロファイルが削除されたり、名前が変更されていないかチェックします。



 a| 
repo -02303
 a| 
プロファイル設定 [%s] の削除に失敗しました
 a| 



 a| 
repo -02403.
 a| 
プロファイル設定 [%s] のエクスポートに失敗しました。エラー [%s]
 a| 



 a| 
repo -02503
 a| 
プロファイル設定 [%s] のインポートに失敗しました。エラー [%s]
 a| 



 a| 
rep2-02603
 a| 
グローバルプロファイルの取得に失敗しました。エラー [%s] が発生しました。
 a| 



 a| 
02606
 a| 
プロファイル [%s] の取得に失敗しました。エラー [%s]
 a| 



 a| 
02703.
 a| 
プロファイルのリストを作成できませんでした。エラー [%s] が発生しました。
 a| 
プロファイルの一覧表示に失敗しましたconfigs フォルダのパスをチェックします。



 a| 
repo_3002
 a| 
設定 [%s] はプロファイル [%s] に対してすでに存在します。
 a| 
同じ名前の構成ファイルが指定されたプロファイルに対してすでに存在します。別の名前を選択してください。



 a| 
03103 と入力します
 a| 
プロファイル [%s] の設定 [%s] の作成に失敗しました。エラー [%s]
 a| 



 a| 
rep2-03203
 a| 
設定 [%s] のプロファイル [%s] の更新に失敗しました。エラー [%s]
 a| 



 a| 
repo -03212
 a| 
構成 [%s] のプロファイル [%s] の名前を [%s] に変更できませんでした
 a| 
プロファイルの構成ファイルの名前を変更できませんでした。構成ファイルが名前変更または削除されていないかチェックし、 Snap Creator を実行しているユーザのディレクトリに対する権限をチェックしてください。



 a| 
03303
 a| 
構成 [%s] をプロファイル [%s] から削除できませんでした
 a| 
configs フォルダにあるプロファイルから構成ファイルを削除できませんでした。Snap Creator を実行しているユーザのディレクトリに対する権限をチェックしてください。



 a| 
03403 と報告されています
 a| 
プロファイル [%s] の設定 [%s] のエクスポートに失敗しました。エラー [%s] が発生しました。
 a| 



 a| 
03503
 a| 
設定 [%s] をプロファイル [%s] にインポートできませんでした。エラー [%s] が発生しました。
 a| 



 a| 
03603.
 a| 
構成 [%s] をプロファイル [%s] から取得できませんでした。エラー [%s] が発生しました。
 a| 



 a| 
03703
 a| 
プロファイル [%s] の設定のリストを作成できませんでした。エラー [%s] が発生しました。
 a| 



 a| 
repo_04003 が表示されます
 a| 
プロファイル [%s] 、構成 [%s] 、およびタイムスタンプ [%s] のカタログの読み取りに失敗しました。エラー [%s] が発生しました。
 a| 



 a| 
repo_04103
 a| 
プロファイル [%s] 、構成 [%s] 、およびタイムスタンプ [%s] のカタログの書き込みに失敗しました。エラー [%s] が発生しました。
 a| 



 a| 
（ 2004 年 4 月現在／ 203
 a| 
プロファイル [%s] 、構成 [%s] 、およびタイムスタンプ [%s] のカタログをパージできませんでした。エラー [%s] が発生しました。
 a| 



 a| 
repo_04303
 a| 
プロファイル [%s] と構成 [%s] のインベントリカタログがエラー [%s] で失敗しました。
 a| 



 a| 
（ 2004 年 4 月現在／ repo
 a| 
設定 [%s] は存在しません
 a| 



 a| 
repo_04309
 a| 
ポリシーオブジェクトの追加に失敗しました [%s]
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo -04313
 a| 
ポリシー ID %s のポリシーオブジェクトを削除できませんでした
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo -04315
 a| 
ポリシーオブジェクトの更新に失敗しました： %s
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo -04316
 a| 
ポリシーをリストできませんでした
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
(04321)
 a| 
バックアップタイプオブジェクト [%s] の追加に失敗しました。
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo_04323
 a| 
バックアップタイプ ID ： %s のバックアップタイプエントリが存在しません
 a| 
有効なバックアップタイプを指定してください。



 a| 
repo -04325
 a| 
バックアップタイプ ID %s のバックアップタイプオブジェクトを削除できませんでした
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo_04327
 a| 
バックアップタイプオブジェクトを更新できませんでした： %s
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo_04328
 a| 
バックアップタイプをリストできませんでした
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo -04333
 a| 
スケジューラジョブオブジェクト [%s] の追加に失敗しました。
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo -04335
 a| 
ジョブ ID ： %s のスケジューラジョブエントリが存在しません
 a| 
有効なスケジューラジョブを渡します。



 a| 
repo -04337
 a| 
ジョブ ID %s のスケジューラジョブオブジェクトを削除できませんでした
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo -04339
 a| 
スケジューラジョブオブジェクトの更新に失敗しました： %s
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo -04340
 a| 
スケジューラジョブをリストできませんでした
 a| 
データベースエラー。詳細についてはスタックトレースを確認してください。



 a| 
repo_04341
 a| 
ポリシーオブジェクトの追加に失敗しました。同じ名前のポリシー [%s] がすでに存在します
 a| 
同じ名前のポリシーがすでに存在します。別の名前でやり直してください。



 a| 
repo_04342
 a| 
バックアップタイプオブジェクトの追加に失敗しました。同じ名前のバックアップタイプ [%s] がすでに存在します
 a| 
同じ名前のバックアップタイプがすでに存在します。別の名前でやり直してください。



 a| 
repo_04343
 a| 
スケジューラオブジェクトの追加に失敗しました。同じタスク名のスケジューラ [%s] がすでに存在します
 a| 



 a| 
repo_04344
 a| 
プロファイル [%s] の更新に失敗しました。プロファイルが空です。
 a| 



 a| 
repo -04345
 a| 
新しいポリシーを追加する場合、ポリシータイプを null にすることはできません
 a| 



 a| 
repo_04346
 a| 
ストレージオブジェクトを null にすることはできません
 a| 



 a| 
(04347)
 a| 
ストレージオブジェクトの追加に失敗しました。同じ名前 / IP のストレージ [%s] がすでに存在します
 a| 



 a| 
repo -04348
 a| 
ストレージの詳細を読み込めませんでした。データベースエラー！
 a| 



 a| 
（ 2004 年 4 月現在／ 349
 a| 
無効なホスト名です。ホスト名 / IP [%s] のストレージは存在しません
 a| 



 a| 
repo -04350
 a| 
ホスト名を null にすることはできません
 a| 
無効なホスト名です



 a| 
repo_04351
 a| 
ストレージ [%s] の削除に失敗しました。エラー [%s]
 a| 
ストレージを削除できませんでした。データベースエラー！



 a| 
repo_04355
 a| 
ストレージ [%s] の更新に失敗しました。エラー [%s]
 a| 
ストレージを更新できませんでした。データベースエラー！



 a| 
repo_04356
 a| 
クラスタオブジェクトを null にすることはできません
 a| 



 a| 
repo_04358
 a| 
ストレージ [%s] の追加に失敗しました。エラー [%s]
 a| 



 a| 
repo -04359
 a| 
クラスタ [%s] の更新に失敗しました。エラー [%s]
 a| 



 a| 
repo_04360
 a| 
クラスタオブジェクトの追加に失敗しました。同じ名前 / IP のクラスタ [%s] がすでに存在します
 a| 
同じホスト名のクラスタがすでに存在します

|===