---
permalink: administration/reference_storage_error_messages.html 
sidebar: sidebar 
keywords: storage troubleshoot, error, message 
summary: ストレージ関連のエラーメッセージは、発生した問題のトラブルシューティングに役立ちます。 
---
= ストレージエラーメッセージ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ関連のエラーメッセージは、発生した問題のトラブルシューティングに役立ちます。

次の表に、エラーコードとメッセージ、およびエラーの簡単な概要と推奨される解決策を示します。

[cols="15,35,50"]
|===
| エラーコード | エラーメッセージです | 説明 / 解決策 


 a| 
ストレージ -00001
 a| 
日付形式 [%s] は無効です： [%s]
 a| 
ボリュームクローンが Snap Creator によって作成されていないか、クローン名に付加されたタイムスタンプが無効です。



 a| 
ストレージ -00002
 a| 
実行者を取得できません
 a| 
ストレージに対して実行者が作成されていません。ログをチェックして、 NetApp Manageability エラーがないか確認します。問題の原因が表示される可能性があります。



 a| 
ストレージ -00003
 a| 
ホストに接続できません
 a| 
ホストにアクセスできません。ローカルのファイアウォールが正しく設定されていること、および Snap Creator サーバがインストールされたシステムからホストが ping を実行できることを確認します。



 a| 
ストレージ -01003
 a| 
イベント ID [%s] 、カテゴリ [%s] 、概要 [%s] 、レベル [%s] 、ホスト名 [%s] の AutoSupport メッセージを作成できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
（ 2004 年 10 月現在／ Storage
 a| 
ファイルをリストアするには、ソースボリュームとデスティネーションボリュームが同じボリュームである必要があります。
 a| 
ソースボリュームとデスティネーションボリュームが異なります。ソースボリュームとデスティネーションボリュームに同じボリュームを指定してください。



 a| 
ストレージ -02003
 a| 
整合グループの Snapshot コピー [%s] のボリューム [%s] での作成に失敗しました。エラー [%s] があります。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02006
 a| 
整合グループの Snapshot コピーを [%s] に CG ID [%s] でコミットできませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02009
 a| 
Snapshot コピー [%s] のボリューム [%s] での作成に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02015
 a| 
Snapshot コピー [%s] のボリューム [%s] の削除に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage - 02021
 a| 
ボリューム [%s] の Snapshot コピー [%s] のリストアに失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02025
 a| 
ファイル [%s] を Snapshot コピー [%s] から [%s] にリストアできませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02028
 a| 
プライマリ SnapVault Snapshot コピースケジュール [%s] のボリューム [%s] での作成に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02034
 a| 
プライマリ SnapVault Snapshot コピーのスケジュールをボリューム [%s] から削除できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage - 02038
 a| 
Snapshot コピー [%s] に基づいてボリューム [%s] のクローン [%s] を作成できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02041
 a| 
Snapshot コピー [%s] に基づいて、ボリューム [%s] から [%s] にファイル [%s] をクローニングできませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02043
 a| 
パス [%s] のファイルのリストを作成できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage - 02046 のようになりました
 a| 
スペースリザベーション [%s] での Snapshot コピー [%s] に基づいて LUN [%s] を [%s] にクローニングできませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02049
 a| 
LUN [%s] をボリューム [%s] から削除できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02052
 a| 
LUN のリストを表示できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02062
 a| 
NFS エクスポート [%s] （ホスト名 [%s] 、アクセス [%s] ）の追加に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02072
 a| 
コントローラ [%s] で SnapMirror ステータスを取得できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02075
 a| 
コントローラ [%s] で SnapMirror 関係を取得できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage - 02082
 a| 
SnapMirror 関係 [%s] を Snapshot コピー [%s] に基づいて更新できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 02092
 a| 
ボリューム [%s] の Snapshot コピーのリストを作成できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage - 02102
 a| 
Snapshot コピー [%s] のボリューム [%s] から [%s] への名前変更に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02112.
 a| 
コントローラ [%s] で SnapVault ステータスを取得できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02115
 a| 
コントローラ [%s] で SnapVault 関係を取得できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02122
 a| 
SnapVault 関係 [%s] を Snapshot コピー [%s] に基づいて更新できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02132
 a| 
ボリューム [%s] に基づいてクローンボリュームのリストを作成できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -0142
 a| 
ボリューム [%s] の削除がエラー [%s] で失敗しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage - 02152
 a| 
ボリュームのリストを表示できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02155
 a| 
ボリューム [%s] のリスト表示に失敗しました。エラーメッセージ [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -02162
 a| 
ボリューム [%s] の Snapshot コピー [%s] のリストアに失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -03001
 a| 
clustered ONTAP ノード [%s] から SVM を取得しています。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -05003
 a| 
NetApp Management Console データセット [%s] の作成に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -05006.
 a| 
データセット [%s] の NetApp Management Console ベースのバックアップをストレージコントローラ [%s] で作成できませんでした。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -05009.
 a| 
データセット [%s] の NetApp Management Console データセットステータスの取得に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage -05012.
 a| 
NetApp Management Console データセット [%s] の検証に失敗しました。エラー [%s] があります。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage -05018
 a| 
OM イベント [%s] を [%s] に作成しています。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -03002
 a| 
igroup [%s] の LUN [%s] へのマッピングに失敗しました。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -03005.
 a| 
LUN [%s] をボリューム [%s] に作成できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -03008.
 a| 
プライマリ SnapVault Snapshot コピー [%s] のボリューム [%s] での作成に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 03011.
 a| 
データセット [%s] の NetApp Management Console バックアップコピーをリストしていますが、エラー [%s] で失敗しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 03014
 a| 
NetApp Management Console バックアップバージョン ID [%s] の削除がエラー [%s] で失敗しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 03019
 a| 
[%s] （ [%s] ）の NetApp Management Console バックアップの開始に失敗しました。終了します。
 a| 
ログにエラーがないかどうかを確認します。 NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 03022
 a| 
ジョブ ID [%s] の NetApp Management Console バックアップの進行状況の開始に失敗しました。終了します。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03025
 a| 
パス [%s] のファイルの削除がエラー [%s] で失敗しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管期間： 03030
 a| 
[%s] で clustered Data ONTAP ノードの検出に失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03033
 a| 
[%s] のシステムバージョンの詳細を取得できませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03036
 a| 
パス [%s] でのディレクトリの作成に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03039
 a| 
パス [%s] のディレクトリの削除に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 03043
 a| 
パス [%s] でのファイルの作成に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage - 03046
 a| 
データセット [%s] の NetApp Management Console データセットの変更に失敗しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03049
 a| 
ファイル [%s] のファイルコンテンツを読み取れませんでした
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03052
 a| 
オプション [%s] の取得に失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03055
 a| 
オブジェクト [%s] のパフォーマンスカウンタの取得に失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03058
 a| 
オブジェクト [%s] のパフォーマンスインスタンスの取得に失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
ストレージ -03061
 a| 
[%s] の NetApp Management Console データセット情報に失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 03064
 a| 
システム CLI コマンド [%s] が失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 03067
 a| 
NetApp Management Console データセット [%s] の削除に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03070
 a| 
SnapVault 関係 [%s] を Snapshot コピー [%s] に基づいてリストアできませんでした。エラー [%s] が発生しました。
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 -03073
 a| 
[%s] の CIFS エクスポートに失敗しました。 [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03076
 a| 
コントローラ [%s] でルートボリュームの取得に失敗しました。エラー [%s]
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 - 03079
 a| 
ボリューム [%s] のジャンクションパスの取得に失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
保管 -03082
 a| 
システム名を取得できませんでした
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 03085
 a| 
コントローラ [%s] での NFS サービスの取得に失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage - 03088
 a| 
ホスト [%s] のパス名 [%s] の権限 [%s] の NFS 権限チェックに失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
storage - 03091.
 a| 
コントローラ [%s] でのネットワークインターフェイスの取得に失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage - 03094
 a| 
ボリューム [%s] の qtree リストに失敗しました
 a| 
ログを参照してエラーがないか確認します。NetApp Manageability エラーが発生している可能性があります。ログに問題の原因が記録されている可能性があります。



 a| 
Storage-04119
 a| 
SVMのリストを表示できませんでした。エラーが
 a| 
ログを参照してエラーがないか確認します。問題の原因 を示すManage ONTAP 解決策 エラーが表示される場合があります。



 a| 
vserver_tunnel_enabledというコマンドを実行します
 a| 
（はい / いいえ）
 a| 
vsimトンネリングを設定します。Yに設定すると、vsimトンネリング機能が有効になります。

|===