---
permalink: administration/reference_logs.html 
sidebar: sidebar 
keywords: snap, creator, error, troubleshoot, cmd, output, debug, warn, error, out, debug, stderr 
summary: Snap Creator では、役立つエラーメッセージとトラブルシューティングログを提供しています。 
---
= エラー・メッセージの種類およびトラブルシューティング・ログです
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator では、役立つエラーメッセージとトラブルシューティングログを提供しています。

Snap Creator により提供されるエラーメッセージの種類は次のとおりです。

* * 情報 *
+
標準的な、通常発生する操作の場合。

* * CMD *
+
Snap Creator が（構成に応じて）実行する外部コマンドまたはスクリプトをログに記録し、コマンドまたはスクリプトからのリターンコードを記録します。PRE 、 POST 、アプリケーションの休止または休止解除コマンドのいずれかを表しているのが一般的です。

* * 出力 *
+
Data ONTAPI ライブラリが呼び出されます。

* * デバッグ *
+
を参照してください。

* * WARN *
+
注意を引くための手段ですが、通常は正常なアクティビティとみなされるため、対処は不要です（ Snapshot コピーを削除する場合など）。

* * エラー *
+
問題があることを示します。多くの場合、エラーの修正に手動のアクションが必要になります。ERROR メッセージが発生すると、 Snap Creator は終了します。再度実行する前に発生した問題を解決することが重要です。Snap Creator では問題は自動的に修正されませんが、構成ファイルに定義されている PRE_EXIT_CMD を使用すれば、 Snap Creator の終了前のアクションを指定できます。



トラブルシューティングログには、 Snap Creator によって実行されるすべての外部コマンドまたはスクリプト（ SnapDrive など）の出力が含まれます。Snap Creator を通じてその他のスクリプトを呼び出す場合は、それらのスクリプトの終了コードおよび出力を適切にセットアップしておくことが重要です。問題が発生した場合は、ステータス 0 で終了しないでください。

Snap Creator のすべてのプロファイルおよび構成で使用可能なログは次のとおりです。

* * OUT *
+
詳細なロギング情報のみを指定します。

* * デバッグ *
+
詳細なロギング情報とデバッグロギング情報が含まれます。トレース・メッセージがデフォルト設定である構成ファイルで有効になっている場合は、トレース情報がこのログに表示されます。トレースメッセージを有効にするパラメータは、 LOG_TRACE_ENABLE - （ Y|N ）です。

* * エラー *
+
指定された構成のすべてのエラーイベントの履歴が含まれます。エラーログは、過去のエラーに関する情報を確認するのに役立ちます。これにより、ユーザはイベントを関連付けて履歴を確認できます。Snap Creator と監視アプリケーションを統合する方法として、監視および使用できます。

* * stderr *
+
Snap Creator コードの問題が発生した場合は情報を含みます。ただし、一般に標準のエラーストリームログは空です。



アウトログ、デバッグログ、および stderr ログは、構成ファイルに定義された LOG_NUM の値に基づいて保持されます。一方エラーログは常に記録されます。すべてのログは /path/to/scServer_v<#>/install_path /engine/logs/profile ディレクトリに書き込まれます。

Snap Creator エージェントは、必要に応じてアウトログ、デバッグログ、および stderr ログも作成します。このログはデフォルトで有効になっており、パラメータは SC_AGENT_LOG_ENABLE = Y に設定されています
