---
permalink: administration/reference_snap_creator_cli_commands_for_workflow_actions.html 
sidebar: sidebar 
keywords: command-line, interface, cli, snap, creator, workflow, command, backup, copy 
summary: Command-Line Interface （ CLI ；コマンドラインインターフェイス）コマンドを使用して、 Graphical User Interface （ GUI ；グラフィカルユーザインターフェイス）に基づいて、 Snap Creator のさまざまなワークフローアクションを実行できます。 
---
= ワークフローアクション用の Snap Creator CLI コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Command-Line Interface （ CLI ；コマンドラインインターフェイス）コマンドを使用して、 Graphical User Interface （ GUI ；グラフィカルユーザインターフェイス）に基づいて、 Snap Creator のさまざまなワークフローアクションを実行できます。

次の表に、 Snap Creator の GUI ベースのワークフローアクションを実行するための CLI コマンドを示します。

|===
| ワークフロー領域 | アクション / 説明 | コマンドおよび関連するパラメータ 


 a| 
バックアップ
 a| 
バックアップコピーを作成する。プロファイルに関連付けられた構成ファイルに基づいてバックアップ処理を実行します。
 a| 
[listing]
----

                  snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backup
--policy Policy
--verbose
----


 a| 
Open Systems SnapVault バックアップを作成します。 Open Systems SnapVault を使用してバックアップ操作を実行します。これには Snap Creator エージェントが必要です。Snap Creator サーバは Snap Creator エージェントと通信し、 SnapVault の更新を実行します。プライマリバックアップコピーは作成されません。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action ossv
--policy Policy
--verbose
---- a| 
バックアップ（続き）



 a| 
バックアップコピーを削除する（手動）。既存のバックアップを手動で削除します。この処理はメニュー方式です。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupDel
--policy Policy
--verbose
---- a| 
バックアップコピーを（自動的に）削除する



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupDel
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
---- a| 
バックアップコピーをリストします。プライマリおよびセカンダリストレージシステム上の Snap Creator バックアップコピーをリストします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action backupList
--policy Policy
--verbose
----


 a| 
バックアップコピーをマウント既存のバックアップに対してマウント処理を実行します。バックアップに基づいたボリュームクローンを作成し、 MOUNT_CMD コマンドを使用して Snap Creator エージェント経由でクローンをマウントできるようにします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action mount
--backupName name
--verbose
---- a| 
バックアップ（続き）



 a| 
バックアップコピーをアンマウントします。既存のバックアップに対してアンマウント処理を実行します。バックアップに基づいたボリュームクローンを削除し、 umount_CMD コマンドを使用して Snap Creator エージェント経由でクローンのアンマウントを可能にします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action umount
--backupName name
--verbose
---- a| 
バックアップタイプ



 a| 
新しいバックアップタイプを作成します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeAdd
--backupTypeName name
--verbose
---- a| 
既存のバックアップタイプを更新する。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeUpdate
--backupTypeId 1
--backupTypeName name
--verbose
---- a| 
既存のバックアップタイプを削除する
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeDelete
--backupTypeId 1

--verbose
----


 a| 
バックアップタイプをリスト表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action backupTypeList
--verbose
---- a| 
クローン



 a| 
LUN のクローン作成：プライマリストレージシステムをバックアップし、 LUN クローンを使用してバックアップをクローニングします。igroup のボリュームのマッピングも処理されます。これには SAN 環境または iSAN 環境が必要です。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneLun
--policy Policy
--verbose
---- a| 
ボリュームをクローニングします。プライマリストレージシステムをバックアップし、ボリュームクローンを使用してバックアップをクローニングします。igroup 、 NFS 、 CIFS のボリュームのマッピングも処理されます。これには、 SAN 、 iSAN 、または NAS 環境が必要です。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneVol
--policy Policy
--verbose
---- a| 
クローンを削除します。指定された保持ポリシーに基づいてクローン削除処理を実行します。LUN クローンのコピーが 1 つだけ保持されます。ボリュームクローンには、ポリシーに関連付けられた使用方法があります。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneDel
--policy Policy
--verbose
----


 a| 
Snap Creator クローンをリストします。指定された構成の Snap Creator のボリュームクローンをリスト表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action cloneList
--verbose
---- a| 
Snap Creator のボリュームをリストします。プライマリストレージシステム上の指定された構成の Snap Creator ボリュームをリストします。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action volumeList
--verbose
---- a| 
構成ファイル
 a| 
構成をインポートします。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action configImport
--importFile file_path
--verbose
---- a| 
設定をエクスポートします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action configExport
--exportFile file_path
--verbose
----


 a| 
グローバル構成ファイルをインポートします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalImport
--importFile file_path
--verbose
---- a| 
グローバル構成ファイルをエクスポートします。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalExport
--ExportFile file_path
--verbose
---- a| 
リポジトリからグローバル構成ファイルを削除します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action globalDelete
--verbose
----


 a| 
構成ファイル（続き）
 a| 
特定のプロファイルのグローバル構成ファイルをリポジトリにインポートします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalImport
--importFile file_path
--verbose
----


 a| 
リポジトリから特定のプロファイルのグローバル構成ファイルをエクスポートします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalExport
--exportFile file_path
--verbose
---- a| 
リポジトリから特定のプロファイルのグローバル構成を削除します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileglobalDelete
--verbose
---- a| 
プロファイル内の古い構成ファイルをアップグレードします。新しく導入されたパラメータを古い構成ファイルに追加します。このコマンドを実行する前に、プロファイルフォルダを指定して scServer/engine/configs フォルダに古い構成ファイルをすべてコピーする必要があります。
 a| 
[listing]
----
snapcreator
--server IP
--port port
--user userid
--passwd password
--upgradeConfigs
--profile profile_name
--verbose
----


 a| 
ジョブ
 a| 
すべてのジョブとそのステータスを一覧表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action jobStatus
--verbose
----


 a| 
ポリシー
 a| 
新しいローカルポリシーを追加します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType local
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
----


 a| 
ポリシー（続き）
 a| 
新しい SnapMirror ポリシーを追加します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType snapmirror
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
----


 a| 
新しい SnapVault ポリシーを追加します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyAdd
--schedId 1
--backupTypeId 1
--policyType snapvault
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--secondaryCount 30
--secondaryAge 0
--verbose
---- a| 
SnapMirror ポリシーを更新します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyUpdate
--policyId 1
--schedId 1
--backupTypeId 1
--policyType snapmirror
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--verbose
---- a| 
ポリシー（続き）
 a| 
SnapVault ポリシーを更新する。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyUpdate
--policyId 1
--schedId 1
--backupTypeId 1
--policyType snapvault
--policyName testPolicy
--primaryCount 7
--primaryAge 0
--secondaryCount 30
--secondaryAge 0
--verbose
---- a| 
ポリシーを削除する。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyDelete
--policyId 1
--verbose
----


 a| 
すべてのポリシーをリスト表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyList
--verbose
---- a| 
特定のポリシーに関する詳細情報を表示します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policyDetails
--policyId 1
--verbose
---- a| 
ポリシーをプロファイルに割り当てます。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyAssignToProfile
--policies testPolicy
--verbose
----


 a| 
ポリシー（続き）
 a| 
プロファイルに対するポリシーの割り当てを元に戻します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyUnassignFromProfile
--verbose
----


 a| 
プロファイルに割り当てられているすべてのポリシーを一覧表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action policyListForProfile
--verbose
---- a| 
ポリシースケジュール



 a| 
毎時ポリシースケジュールを作成します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--verbose
---- a| 
日次ポリシースケジュールを作成します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
ポリシースケジュール（続き）
 a| 
週次ポリシースケジュールを作成します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
cron ポリシースケジュールを作成します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedAdd
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron '0 0/5 14,18 * * ?'
--schedActive true
--verbose
----


 a| 
ポリシーの毎時スケジュールを更新します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--verbose
---- a| 
ポリシースケジュール（続き）



 a| 
日次ポリシースケジュールを更新する。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
週次ポリシーのスケジュールを更新する。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--verbose
---- a| 
cron ポリシースケジュールを更新してください。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedUpdate
--schedId 1
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron '0 0/5 14,18 * * ?'
--schedActive true
--verbose
----


 a| 
ポリシースケジュール（続き）
 a| 
ポリシースケジュールを削除する。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedDelete
--schedId 1
--verbose
----


 a| 
ポリシーのスケジュールをリストします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedList
--verbose
---- a| 
ポリシースケジュールに関する追加情報を表示します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action policySchedDetails
--schedId 1
--verbose
---- a| 
プロファイル
 a| 
新しいプロファイルを作成します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileCreate
--verbose
---- a| 
プロファイルを削除します。 * 注： * プロファイル内の構成ファイルも削除されます。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--action profileDelete
--verbose
----


 a| 
リストア
 a| 
対話型のリストアを実行します。指定されたポリシーに対し、対話型のファイルリストア処理または対話型のボリュームリストア処理を実行します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
----


 a| 
非対話型のボリュームリストアを実行します。は、非対話型のボリュームリストアを実行します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
---- a| 
非対話型ファイルのリストアを実行します。非対話型ファイルのリストアを実行します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action restore
--policy Policy
--verbose
--nonInteractive
--cntName controller
--volName volume
--backupName name
--files file_path1,file_path2,etc.
---- a| 
スケジュール
 a| 
新しい毎時スケジュールを作成します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName HourlyBackup
--schedFreqId 2
--schedActionId 1
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
新しい日次スケジュールを作成します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName DailyBackup
--schedFreqId 3
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
----


 a| 
新しい週次スケジュールを作成します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName WeeklyBackup
--schedFreqId 4
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
スケジュール（続き）



 a| 
新しい cron スケジュールを作成します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedCreate
--policy Policy
--schedName CronBackup
--schedFreqId 5
--schedActionId 1
--schedCron "0 0/5 14,18 * * ?"
--schedActive true
--schedStartDate date
--verbose
---- a| 
スケジュールを実行します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedRun
--schedId 1
--verbose
---- a| 
スケジュールを削除します
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedDelete
--schedId 10
--verbose
----


 a| 
毎時スケジュールを更新します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName HourlyBackup
--schedFreqId 2
--schedId 1
--schedActionId 1
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
スケジュール（続き）



 a| 
日次スケジュールを更新してください。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName DailyBackup
--schedFreqId 3
--schedId 1
--schedActionId 1
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
週次スケジュールを更新します。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName WeeklyBackup
--schedFreqId 4
--schedId 1
--schedActionId 1
--schedDayOfWeek day_of_week
--schedHour hour
--schedMin minute
--schedActive true
--schedStartDate date
--verbose
---- a| 
cron スケジュールを更新してください。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action schedUpdate
--policy Policy
--schedName CronBackup
--schedFreqId 5
--schedId 1
--schedActionId 1
--schedCron "0 0/5 14,18 * * ?"
--schedActive true
--schedStartDate date
--verbose
----


 a| 
スケジュール（続き）
 a| 
すべてのスケジュールを一覧表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedList
--verbose
----


 a| 
サポートされているスケジューラ操作をリストします
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedActionList
--verbose
---- a| 
サポートされているスケジューラ頻度をリストします



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedFreqList
--verbose
---- a| 
スケジュール ID の詳細を表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action schedDetails
--schedId 1
--verbose
----


 a| 
scdump
 a| 
scdump ファイルを作成します。このファイルは、 Snap Creator の root ディレクトリにある scdump という名前の .zip ファイルに、特定のプロファイルに関するログ、構成ファイル、サポート情報をダンプします。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
-- profile Profile
--config Config
--action scdump
--policy Policy
--verbose
----


 a| 
Snap Creator サーバおよびエージェント
 a| 
Snap Creator サーバで認識されているすべてのエージェントのステータスを一覧表示します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action agentStatus
--verbose
----


 a| 
Snap Creator サーバおよびエージェント（続き）
 a| 
Snap Creator サーバに ping を実行します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action pingServer
--verbose
----


 a| 
Snap Creator エージェントに ping を実行します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--action pingAgent
--agentName host_name
--agentPort port
--verbose
---- a| 
Archive サービスの略



 a| 
構成ファイルの設定に従ってアーカイブログ管理を実行します。この処理には Snap Creator エージェントが必要です。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action arch
--verbose
---- a| 
データ保護機能



 a| 
特定の構成に対して NetApp Management Console のデータ保護機能データセットを設定します。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action pmsetup
--verbose
---- a| 
コントローラの SnapVault 関係と SnapMirror 関係のデータ保護ステータスを表示します。SnapVault または SnapMirror が設定されていない場合、結果は表示されません。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action dpstatus
--verbose
---- a| 
休止または休止解除
 a| 
特定のアプリケーションに対して休止処理を実行します。この処理には Snap Creator エージェントが必要です。



 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action quiesce
--verbose
---- a| 
指定されたアプリケーションに対して休止解除処理を実行します。この処理には Snap Creator エージェントが必要です。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action unquiesce
--verbose
----


 a| 
調査
 a| 
特定のアプリケーションの検出を実行します。この処理には Snap Creator エージェントが必要です。
 a| 
[listing]
----
snapcreator
--server IP
--port Port
--user User
--passwd Password
--profile Profile
--config Config
--action discover
--verbose
----
|===