---
permalink: administration/task_customizing_the_default_keystore.html 
sidebar: sidebar 
keywords: keystore, certificate, keytool, windows, unix 
summary: Windows および UNIX で使用できる keytool コマンドを使用して、デフォルトのキーストアまたは証明書をカスタマイズできます。 
---
= デフォルトのキーストアのカスタマイズ
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows および UNIX で使用できる keytool コマンドを使用して、デフォルトのキーストアまたは証明書をカスタマイズできます。

keytool コマンドは Java で提供されます。環境によっては、 keytool コマンドを実行するために Java のインストールディレクトリに切り替える必要があります。

Snap Creator では、トラストストアはサポートされません。

. Snap Creator エージェントを停止します。
. 単一の証明書で新しいキーストアを生成します。
+
keytool -genkeypair -alias alias_name -keystore keystore.file -keypass private_key_password -storepass keystore.password

+
keytool -genkeypair -alias servicekey -keystore serviceKeystore.JKS -keypass kypswd123 -storepass kystrpswd123

. キーストアファイルを scAgent4.3.0 の /etc/directory にコピーします
. Snap Creator エージェントの構成ファイル（ scAgent4.3.0 /etc/allowed_command.config ）で、 keystore.file=keystore.file および keystore.pass = キーストアのパスワードパラメータを更新します。
. Snap Creator エージェントを起動します。


* 関連情報 *

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[Windows での Snap Creator エージェントの起動、検証、停止]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[UNIX 上での Snap Creator エージェントの起動、検証、停止]
