---
permalink: administration/task_creating_configuration_files_using_sc_gui.html 
sidebar: sidebar 
keywords: configuration, file, wizard, gui, management 
summary: 設定ウィザードを使用して構成ファイルを作成できます。 
---
= 構成ファイルを作成しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定ウィザードを使用して構成ファイルを作成できます。

. Snap Creator の GUI のメインメニューで、 * Management * > * Configurations * を選択します。
. [ プロファイルと構成 ] ペインで、新しい構成ファイルを配置するプロファイルを右クリックし、 [ 新しい構成 *] を選択します。
+
右側のペインに設定ウィザードが開きます。

. 
+
.. Configuration ページで、構成ファイルの名前を入力します。
+

NOTE: デフォルトでは、構成ファイルにパスワードがクリアテキストで表示されないように、パスワード暗号化が有効になっています。

.. [ プラグインの種類 ] ページで、プラグインの種類を選択します。
+
設定ウィザードで表示されるページは、選択したオプションによって異なります。

+
|===
| プラグインタイプオプション | 次のページ | 次のページ 


 a| 
アプリケーションプラグイン
 a| 
* アプリケーションプラグイン * 設定するプラグインを選択します。
 a| 
* プラグインパラメータ * は、選択したプラグイン・オプションに関連する設定の詳細を提供します。



 a| 
仮想化プラグイン
 a| 
* 仮想化プラグイン * 設定するプラグインを選択します。
 a| 
* プラグインパラメータ * は、選択したプラグイン・オプションに関連する設定の詳細を提供します。



 a| 
コミュニティプラグイン
 a| 
* コミュニティプラグイン * 設定するプラグインを選択します。
 a| 
* プラグインパラメータ * は、選択したプラグイン・オプションに関連する設定の詳細を提供します。



 a| 
なし（プラグインを使用していない場合）
 a| 
* エージェント設定 *
 a| 
--

--
|===
+
プラグインパラメータおよび設定の詳細については、プラグインのドキュメントを参照してください。

.. Agent Configuration ページで、 Snap Creator エージェントの設定情報を入力します。
.. Storage Connection Settings ページで、転送タイプ（ HTTP または HTTPS ）を選択します。
+
選択した転送タイプの標準ポートが表示されます。ストレージシステムで非標準ポートが使用されている場合は、ポートのフィールドにポート情報を入力します。

.. コントローラ / SVM のクレデンシャルページで、この構成ファイルにボリュームが含まれている各ストレージコントローラの IP アドレスとログインクレデンシャルを入力します。
+

NOTE: 構成には、少なくとも 1 台のストレージコントローラまたは SVM を追加する必要があります。

.. Controller/Vserver Volumes （コントローラ / Vserver ボリューム）ペインで、含める各ボリュームを選択し、右ペインにドラッグするか右矢印をクリックしてボリュームを右ペインに移動し、 * Save （保存） * をクリックします。
+

IMPORTANT: SnapMirror または SnapVault デスティネーションに Snapshot コピーをレプリケートする場合は、この手順で入力する SVM の名前が SnapMirror 関係または SnapVault 関係を作成したときに使用した SVM の名前とまったく同じである必要があります。関係の作成時に完全修飾ドメイン名を指定した場合は、この手順で、指定した情報を使用して Snap Creator が SVM を検出できるかどうかに関係なく、完全修飾ドメイン名を指定する必要があります。名前（大文字または小文字）に使用するケースは重要です。

+
プライマリストレージシステム上の SVM の名前を確認するには、 snapmirror show コマンドを使用します。

+
[listing]
----
snapmirror show -destination-path destination_SVM:destination_volume
----
+
destination_svm_name はデスティネーションシステム上の SVM の名前で、 destination_volume はボリュームです。

.. コントローラのクレデンシャルページで、コントローラが正しい情報を表示していることを確認します。
+
変更が必要な場合は、コントローラを選択し、 * Edit * をクリックします。

.. Snapshot の詳細ページで、 Snapshot コピーの詳細を指定します。
+
|===
| フィールド | 説明 


 a| 
Snapshot コピー名
 a| 
Snapshot コピー名を指定できます。通常、 Snapshot コピーには構成ファイルと同じ名前を付けますが、 Snapshot コピー名にはバックアップ中のデータが含まれる場合があります。

+ 注： Snapshot コピー名には特殊文字は使用しないでください。



 a| 
Snapshot コピーラベル
 a| 
Snapshot コピーラベルを指定できます。このオプションは、 clustered Data ONTAP 8.2 以降で有効です。clustered Data ONTAP 8.2 より前の Data ONTAP リリースでは、このフィールドに機能は表示されません。



 a| 
ポリシータイプ
 a| 
ポリシータイプを選択できます。次の 2 つのオプションがあります。

*** Policy ：このオプションは、 Snapshot コピーポリシー領域に表示される組み込みのポリシーの 1 つを有効にして、保持期間（保持するバックアップの数）を指定します。
*** ポリシーオブジェクトを使用：ポリシーオブジェクトがすでに作成されている場合は、このオプションを選択する必要があります。




 a| 
Snapshot コピーポリシー
 a| 
有効にするポリシーを選択できます



 a| 
Snapshot コピーの削除を防止
 a| 
Snapshot コピーの削除を禁止するかどうかを指定できます



 a| 
ポリシー保持期間
 a| 
ポリシーの保持期間を指定できます



 a| 
命名規則
 a| 
バックアップの命名規則（ Recent または Timestamp ）を指定できます。SAP HANA 、 Vibe 、 Domino などのプラグインでは、「 Recent 」はサポートされていません。

[+]

|===
.. スナップショットの詳細（続き）ページで、ご使用の環境に適用可能なその他の設定を行います。
.. データ保護ページで、 SnapMirror 処理または SnapVault 処理との統合が必要かどうかを選択します。
+
SnapMirror または SnapVault テクノロジを選択した場合は、追加情報が必要です。SnapMirror および SnapVault テクノロジの場合は、 IP アドレスではなく、ストレージシステム名を指定する必要があります。

.. DFM / OnCommand の設定ページで、 Snap Creator 構成と NetApp OnCommand 管理ツールを統合する場合は、を選択して詳細を指定します。
.. 概要を確認し、 [ 完了 ] をクリックします。



