---
permalink: administration/task_setting_snap_creator_server_credentials.html 
sidebar: sidebar 
keywords: snap, creator, server, credentials, scadmin, port 
summary: Snap Creator サーバのクレデンシャル（サーバのホスト名または IP アドレス、ポート、ユーザ、パスワードの設定など）を保存しておくと、コマンドラインインターフェイス（ CLI ）に複数回クレデンシャルを入力するのを防ぐことができます。必要に応じて、保存されているクレデンシャルを削除できます。 
---
= Snap Creator サーバのクレデンシャルの設定
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator サーバのクレデンシャル（サーバのホスト名または IP アドレス、ポート、ユーザ、パスワードの設定など）を保存しておくと、コマンドラインインターフェイス（ CLI ）に複数回クレデンシャルを入力するのを防ぐことができます。必要に応じて、保存されているクレデンシャルを削除できます。

Snap Creator サーバのクレデンシャルを設定する手順は、 Windows と UNIX で同じです。次の手順では、 UNIX 環境の例を使用します。

. Snap Creator サーバがインストールされているホスト上で、 Snap Creator サーバのインストールディレクトリから次のコマンドを入力します。
+
「 /install_path/scServer4.3/snapcreator -- credentials

+
次の出力が表示され、 Snap Creator サーバのデフォルトクレデンシャルを設定できるようになりました。

+
[listing]
----
Enter user: SCadmin

Enter password:

Enter Snap Creator server hostname or IP [localhost]:
Enter Snap Creator server port [8443]:
Enter Profile name ( or * for any profile: *
Enter Config name ( or * for any config: *
----
. 各エントリに適切な情報を入力します。
+
Config name エントリの入力が完了すると、クレデンシャルが保存され、「 Info ： CLI credentials stored successfully 」というメッセージが表示されます。クレデンシャルは、 snapcreator .credentials ファイル内の .snapcreatordirectory またはホームディレクトリ内のフォルダに保存されています。

. 保存されているクレデンシャルを削除する場合は、 snapcreator .credentials ファイルを削除してください。

