---
permalink: administration/task_creating_global_configuration_files.html 
sidebar: sidebar 
keywords: global, configuration, storage, controller, file, create, backup, super, profile 
summary: グローバル構成ファイルを作成して、ストレージコントローラ、 Storage Virtual Machine （ SVM ）、または VMware クレデンシャル設定をバックアップポリシーから分離できます。 
---
= グローバル構成ファイルを作成しています
:icons: font
:imagesdir: ../media/


[role="lead"]
グローバル構成ファイルを作成して、ストレージコントローラ、 Storage Virtual Machine （ SVM ）、または VMware クレデンシャルの設定をバックアップポリシーと分離できます。

グローバル構成ファイルを使用すると、アクセスを制御し、バックアップおよびリストア処理を実行できます。

次の 2 種類のグローバル構成ファイルを作成できます。

* * スーパーグローバル *
+
この設定では、すべてのプロファイルのすべての設定が環境されます。

* * プロファイルグローバル *
+
この構成では、プロファイル内に作成されたすべての構成が環境されます。

+
.. Snap Creator の GUI のメインメニューで、 * Management * > * Global Configurations * を選択します。
.. グローバル構成ペインで、 * グローバル作成 * をクリックします。
+
右側のペインにグローバル構成の設定ウィザードが開きます。

.. 設定ウィザードに入力して構成ファイルを作成します。
+
... [*Configuration*] ページで、グローバルコンフィギュレーションタイプ（ [Super Global] または [Profile Global] ）を選択します。
+
構成ファイルの名前は、デフォルトでグローバルに設定されています。この名前は変更できません。

+
グローバル構成タイプとして Profile Global を選択した場合は、プロファイルを選択します。

+

NOTE: デフォルトでは、構成ファイルにパスワードがクリアテキストで表示されないように、パスワード暗号化が有効になっています。

... [ プラグインの種類 ] ページで、プラグインの種類を選択します。
+
ウィザードで表示されるページは、選択したオプションによって異なります。

+
|===
| プラグインタイプオプション | 次のページ | 次のページ 


 a| 
仮想化プラグイン
 a| 
* 仮想化プラグイン * 設定するプラグインを選択します。
 a| 
* 認証情報 * 選択したプラグイン・オプションの認証情報を入力します。



 a| 
なし
 a| 
* ストレージ接続設定 *
 a| 
--

--
|===
+
プラグインクレデンシャルの詳細については、プラグインのドキュメントを参照してください。

... Storage Connection Settings ページで、転送タイプ（ HTTP または HTTPS ）を選択します。
+
選択した転送タイプの標準ポートが表示されます。ストレージシステムで非標準ポートが使用されている場合は、ポートのフィールドにポート情報を入力します。

... コントローラ / SVM のクレデンシャルページで、この構成ファイルにボリュームが含まれている各ストレージコントローラまたは SVM の IP アドレスとログインクレデンシャルを入力します。
+

NOTE: 構成には、少なくとも 1 台のストレージコントローラまたは SVM を追加する必要があります。

... コントローラのクレデンシャルページで、コントローラが正しい情報を表示していることを確認します。
+
変更が必要な場合は、コントローラを選択し、 * Edit * をクリックします。

... DFM / OnCommand の設定ページで、 Snap Creator 構成と NetApp OnCommand 管理ツールを統合する場合は、を選択して詳細を指定します。
... 概要を確認し、 [ 完了 ] をクリックします。





