---
permalink: installation/reference_cli_command_for_creating_cluster_roles.html 
sidebar: sidebar 
keywords: cli, commands, creating, cluster, roles, role create 
summary: 次の表に、新しいクラスタユーザのロールを作成するのに必要なコマンドを示します。 
---
= クラスタロールを作成するための CLI コマンド
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
次の表に、新しいクラスタユーザのロールを作成するのに必要なコマンドを示します。

|===
| コマンドディレクトリ名 | 実行するコマンド 


 a| 
cluster identity show の実行
 a| 
role create -role CRBAC_New -cmddirname "cluster identity show " -vserver clus3240rre



 a| 
イベント
 a| 
role create -role CRBAC_New -cmddirname "event" -vserver clus3240rre



 a| 
イベント構成
 a| 
role create -role CRBAC_New -cmddirname "event config" -vserver clus3240rre



 a| 
イベントの送信先
 a| 
role create -role CRBAC_New -cmddirname "event destination" -vserver clus3240rre



 a| 
イベントログ
 a| 
role create -role CRBAC_New -cmddirname "event log" -vserver clus3240rre



 a| 
イベントのメール履歴
 a| 
role create -role CRBAC_New -cmddirname "event mailhistory" -vserver clus3240rre



 a| 
イベントルート
 a| 
role create -role CRBAC_New -cmddirname "event route" -vserver clus3240rre



 a| 
イベントのフィリストーリー
 a| 
role create -role CRBAC_New -cmddirname "event snmphistory " -vserver clus3240rre



 a| 
イベントステータス
 a| 
role create -role CRBAC_New -cmddirname "event status" -vserver clus3240rre



 a| 
LUN のコメント
 a| 
role create -role CRBAC_New -cmddirname "LUN comment" -vserver clus3240rre



 a| 
lun create をクリックします
 a| 
role create -role CRBAC_New -cmddirname "lun create " -vserver clus3240rre



 a| 
lun delete
 a| 
role create -role CRBAC_New -cmddirname "lun delete " -vserver clus3240rre



 a| 
LUN ジオメトリ
 a| 
role create -role CRBAC_New -cmddirname "LUN geometry" -vserver clus3240rre



 a| 
LUN igroup add
 a| 
role create -role CRBAC_New -cmddirname "lun igroup add " -vserver clus3240rre



 a| 
lun igroup create を追加します
 a| 
role create -role CRBAC_New -cmddirname "lun igroup create " -vserver clus3240rre



 a| 
LUN igroup セット
 a| 
role create -role CRBAC_New -cmddirname "lun igroup set" -vserver clus3240rre



 a| 
lun igroup show を参照してください
 a| 
role create -role CRBAC_New -cmddirname "lun igroup show " -vserver clus3240rre



 a| 
LUN マップ
 a| 
role create -role CRBAC_New -cmddirname "LUN map" -vserver clus3240rre



 a| 
lun mapping show
 a| 
role create -role CRBAC_New -cmddirname "lun mapping show " -vserver clus3240rre



 a| 
lun modify を追加します
 a| 
role create -role CRBAC_New -cmddirname "lun modify " -vserver clus3240rre



 a| 
LUN の移動
 a| 
role create -role CRBAC_New -cmddirname "LUN move" -vserver clus3240rre



 a| 
LUN はオフラインです
 a| 
role create -role CRBAC_New -cmddirname "LUN offline" -vserver clus3240rre



 a| 
LUN はオンラインです
 a| 
role create -role CRBAC_New -cmddirname "LUN online" -vserver clus3240rre



 a| 
LUN のサイズ変更
 a| 
role create -role CRBAC_New -cmddirname "LUN resize " -vserver clus3240rre



 a| 
lun show をクリックします
 a| 
role create -role CRBAC_New -cmddirname "lun show " -vserver clus3240rre



 a| 
LUN のマッピング解除
 a| 
role create -role CRBAC_New -cmddirname "lun unmap " -vserver clus3240rre



 a| 
ネットワーク
 a| 
role create -role CRBAC_New -cmddirname "network" -vserver clus3240rre



 a| 
network fcp adapter show コマンドを入力します
 a| 
role create -role CRBAC_New -cmddirname "network fcp adapter show" -vserver clus3240rre



 a| 
network interface show の略
 a| 
role create -role CRBAC_New -cmddirname "network interface show " -vserver clus3240rre



 a| 
security login role show と表示されます
 a| 
role create -role CRBAC_New -cmddirname "security login role show " -vserver clus3240rre



 a| 
security login show のページにアクセスします
 a| 
role create -role CRBAC_New -cmddirname "security login show" -vserver clus3240rre



 a| 
SnapMirror
 a| 
role create -role CRBAC_New -cmddirname "snapmirror" -vserver clus3240rre



 a| 
ストレージアグリゲート
 a| 
role create -role CRBAC_New -cmddirname "storage aggregate" -vserver clus3240rre



 a| 
system license show コマンドを実行します
 a| 
role create -role CRBAC_New -cmddirname "system license show " -vserver clus3240rre



 a| 
システムノード
 a| 
role create -role CRBAC_New -cmddirname "system node" -vserver clus3240rre



 a| 
System node AutoSupport の略
 a| 
role create -role CRBAC_New -cmddirname "system node AutoSupport " -vserver clus3240rre



 a| 
システムノード AutoSupport が起動します
 a| 
role create -role CRBAC_New -cmddirname "system node AutoSupport Invoke-Na" -vserver clus3240rre



 a| 
system node show のコマンドです
 a| 
role create -role CRBAC_New -cmddirname "system node show" -vserver clus3240rre



 a| 
システムノードを実行します
 a| 
role create -role CRBAC_New -cmddirname "system node run " -vserver clus3240rre



 a| 
システムサービス NDMP
 a| 
role create -role CRBAC_New -cmddirname "system services ndmp " -vserver clus3240rre



 a| 
バージョン
 a| 
role create -role CRBAC_New -cmddirname "version" -vserver clus3240rre



 a| 
バージョン
 a| 
security login role create -role bainew1 -vserver SnapCreator -cmddirname " -version " -access readonly



 a| 
vserver export-policy rule create
 a| 
role create -role CRBAC_New -cmddirname 「 vserver export-policy rule create 」 -vserver clus3240rre



 a| 
vserver export-policy rule show
 a| 
role create -role CRBAC_New -cmddirname "vserver export-policy rule show " -vserver clus3240rre



 a| 
vserver export-policy show のコマンドを入力します
 a| 
role create -role CRBAC_New -cmddirname "vserver export-policy show " -vserver clus3240rre



 a| 
SVM FCP
 a| 
role create -role CRBAC_New -cmddirname "vserver fcp " -vserver Snapcreator -vserver clus3240rre



 a| 
vserver fcp initiator show のコマンドを入力します
 a| 
role create -role CRBAC_New -cmddirname "vserver fcp initiator show" -vserver clus3240rre



 a| 
vserver fcp show のコマンドです
 a| 
role create -role CRBAC_New -cmddirname "vserver fcp show" -vserver clus3240rre



 a| 
SVM の FCP ステータス
 a| 
role create -role CRBAC_New -cmddirname "vserver fcp status" -vserver clus3240rre



 a| 
vserver iscsi connection show
 a| 
role create -role CRBAC_New -cmddirname 「 vserver iscsi connection show 」 -vserver clus3240rre



 a| 
Vserver iSCSI
 a| 
role create -role CRBAC_New -cmddirname 「 vserver iscsi 」 -vserver Snapcreator -vserver clus3240rre



 a| 
vserver iscsi interface accesslist add
 a| 
role create -role CRBAC_New -cmddirname 「 vserver iscsi interface accesslist add 」 -vserver clus3240rre



 a| 
vserver iscsi interface accesslist show を実行します
 a| 
role create -role CRBAC_New -cmddirname "vserver iscsi interface accesslist show " -vserver clus3240rre



 a| 
SVM iSCSI ノード名
 a| 
role create -role CRBAC_New -cmddirname "vserver iscsi nodename " -vserver clus3240rre



 a| 
vserver iscsi session show のコマンド
 a| 
role create -role CRBAC_New -cmddirname "vserver iscsi session " show -vserver clus3240rre



 a| 
vserver iscsi show のコマンドです
 a| 
role create -role CRBAC_New -cmddirname "vserver iscsi show " -vserver clus3240rre



 a| 
SVM の iSCSI ステータス
 a| 
role create -role CRBAC_New -cmddirname "vserver iscsi status " -vserver clus3240rre



 a| 
Vserver NFS
 a| 
role create -role CRBAC_New -cmddirname 「 vserver nfs 」 -vserver Snapcreator -vserver clus3240rre



 a| 
SVM の NFS ステータス
 a| 
role create -role CRBAC_New -cmddirname "vserver nfs status" -vserver clus3240rre



 a| 
SVM のオプション
 a| 
role create -role CRBAC_New -cmddirname "vserver options " -vserver clus3240rre



 a| 
vserver services unix-group create
 a| 
role create -role CRBAC_New -cmddirname 「 vserver services name-service unix-group create 」 -vserver clus3240rre



 a| 
vserver services unix-user create
 a| 
role create -role CRBAC_New -cmddirname 「 vserver services name-service unix-user create 」 -vserver clus3240rre



 a| 
vserver services unix-group show
 a| 
role create -role CRBAC_New -cmddirname 「 vserver services name-service unix-group show 」 -vserver clus3240rre



 a| 
vserver services unix-user show のコマンドを使用します
 a| 
role create -role CRBAC_New -cmddirname 「 vserver services name-service unix-user show 」 -vserver clus3240rre



 a| 
vserver show のコマンドです
 a| 
role create -role CRBAC_New -cmddirname "vserver show " -vserver clus3240rre



 a| 
ボリュームのオートサイズ
 a| 
role create -role CRBAC_New -cmddirname "volume autosize " -vserver clus3240rre



 a| 
volume clone create を実行します
 a| 
role create -role CRBAC_New -cmddirname "volume clone create" -vserver clus3240rre



 a| 
volume create を実行します
 a| 
role create -role CRBAC_New -cmddirname "volume create" -vserver clus3240rre



 a| 
ボリュームを削除します
 a| 
role create -role CRBAC_New -cmddirname "volume destroy" -vserver clus3240rre



 a| 
volume efficiency off コマンドを実行します
 a| 
role create -role CRBAC_New -cmddirname "volume efficiency off " -vserver clus3240rre



 a| 
ボリューム効率化
 a| 
role create -role CRBAC_New -cmddirname "volume efficiency on " -vserver clus3240rre



 a| 
volume efficiency show のコマンドです
 a| 
role create -role CRBAC_New -cmddirname "volume efficiency show " -vserver clus3240rre



 a| 
ボリューム効率化が開始されます
 a| 
role create -role CRBAC_New -cmddirname "volume efficiency start" -vserver clus3240rre



 a| 
ボリュームファイル
 a| 
role create -role CRBAC_New -cmddirname "volume file" -vserver clus3240rre



 a| 
volume file clone create を実行します
 a| 
role create -role CRBAC_New -cmddirname "volume file clone create " -vserver clus3240rre



 a| 
volume file show-disk-usage
 a| 
role create -role bainew1 -vserver SnapCreator -cmddirname "volume file show -disk -usage" -access all



 a| 
volume modify を使用します
 a| 
role create -role CRBAC_New -cmddirname "volume modify" -vserver clus3240rre



 a| 
ボリュームはオフラインです
 a| 
role create -role CRBAC_New -cmddirname "volume offline " -vserver clus3240rre



 a| 
volume show のコマンドです
 a| 
role create -role CRBAC_New -cmddirname "volume show" -vserver clus3240rre



 a| 
ボリュームサイズ
 a| 
role create -role CRBAC_New -cmddirname "volume size" -vserver clus3240rre



 a| 
volume snapshot create を実行します
 a| 
role create -role CRBAC_New -cmddirname "volume snapshot create" -vserver clus3240rre



 a| 
ボリュームのアンマウント
 a| 
role create -role CRBAC_New -cmddirname "volume unmount " -vserver clus3240rre

|===