---
permalink: installation/task_installing_the_snap_creator_agent_on_unix.html 
sidebar: sidebar 
keywords: installing, install, snap, creator, agent, unix 
summary: Snap Creator エージェントは、あらゆるオープンシステムプラットフォーム（ AIX 、 HP-UX 、 Linux 、 Solaris ）で動作します。 
---
= UNIX ベースのシステムへの Snap Creator エージェントのインストール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator エージェントは、あらゆるオープンシステムプラットフォーム（ AIX 、 HP-UX 、 Linux 、 Solaris ）で動作します。

JRE 1.8 Update 72 以降がインストールされている必要があります。詳細については、 Snap Creator サーバへの Java のインストールに関する関連リンクを参照してください。

インストールを実行するユーザーは、十分なアクセス権と権限を持っている必要があります。

Snap Creator エージェントのデフォルトポートは 9090 とします。netstat または類似のツールを使用して、ネットワークポート（ 9090 または使用するポート）がすでに使用可能でないことを確認します（たとえば、「 netstat -nap|grep 9090 」と入力します）。

Snap Creator はダウンロード済みである必要があります。詳細については、 Snap Creator ソフトウェアのダウンロードに関する情報を参照してください。

ここでは、 Linux をサンプルプラットフォームとして使用しています。

. ダウンロードした Snap Creator の tar.gz ファイルを、 Snap Creator エージェントのインストール先にコピーします。
+

NOTE: IBM Domino プラグインを使用する場合は、 Domino データフォルダ以外の場所を選択してください。

+
.. サブディレクトリを作成するには、ディレクトリ名を指定して次のコマンドを入力します。
+
[listing]
----
mkdir snap_creator_directory
----
+
[listing]
----
mkdir /SC_41
----
.. 次のコマンドを入力して、新しく作成したディレクトリに Snap Creator の tar.gz ファイルをコピーします。
+
[listing]
----
cp NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
/snap_creator_directory
----
+
[listing]
----
cp NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
/SC_41
----


. Snap Creator Framework の .tar ファイルが格納されているディレクトリに移動し、次のコマンドを入力してファイルを展開します。
+

NOTE: UNIX 環境によっては、 tar コマンドを入力する前にファイルを解凍しなければならない場合があります。

+
[listing]
----
cd snap_creator_directory
tar -xvf NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
----
+
** snap_creator_directory は、 Snap Creator のインストール先です。
** release は、 Snap Creator ソフトウェアパッケージの現在のリリースです。
** OS はオペレーティングシステムです。
+
[listing]
----
cd /sc_41
tar -xvf NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
----


+
これにより、サーバとエージェントの両方のソフトウェアが抽出されます。通常、 Snap Creator サーバのみが設定されます。エージェントは通常、次の例に示すように、保護対象のデータベースまたはアプリケーションサーバ上に存在します。

+
[+]

+
[listing]
----
NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz  scServer4.1.0
scAgent4.1.0
----
. 次のコマンドを入力し、例に示すプロンプトに対して応答して、 Snap Creator エージェントをセットアップします。
+
[listing]
----
cd scAgent*
./snapcreator --setup
Welcome to the NetApp Snap Creator Framework release-version!
\#\#\# Installation options \#\#\#
01. NetApp Snap Creator Framework release-version Agent
Select install option (enter a number or "q" to quit): <Enter 01>

END USER LICENSE AGREEMENT
<...the EULA displays...>

Do you accept the End User License Agreement (y|n): <Enter y>

Enter Snap Creator server port [9090]: <Enter agent port>

INFO: Updated NetApp Snap Creator Framework release-version
/install_path/scAgentrelease-version/engine/etc/agent.properties


INFO: To start scAgent please do the following:

/install_path/scAgentrelease-version/bin/scAgent start
----
. Snap Creator エージェントを起動します。
+
[listing]
----
/install_path/scAgentrelease-version/bin/scAgent start
----
+

NOTE: Snap Creator エージェントを起動時に自動的に実行するには、スクリプトに start コマンドを追加します。

+
スクリプトを作成する手順は、使用するオペレーティングシステムや、サーバを管理するシステム管理者の設定によって多少異なります。一般に、 Snap Creator エージェントの start コマンドは、 /path/to/rc2.d サブディレクトリにある S9 （ S99scAgent など）で始まるファイルに追加できます。rc2.d サブディレクトリは一般に /etc/下 にありますが、これはホストオペレーティングシステムとサーバの特定の構成によって異なる場合があります。詳細については、使用しているオペレーティングシステムのドキュメントを参照してください。

+
次のメッセージが表示されます。

+
[listing]
----
Starting scAgent:
    Watchdog: Running
       Agent: Running
----


* 関連情報 *

xref:task_installing_java_on_snap_creator_hosts.adoc[Snap Creator ホストに Java をインストールしています]

xref:task_downloading_the_snap_creator_software.adoc[Snap Creator ソフトウェアのダウンロード]
