---
permalink: installation/task_uninstalling_snap_creator_server_on_unix.html 
sidebar: sidebar 
keywords: uninstalling, uninstall, snap, creator, server, unix 
summary: Snap Creator サーバを UNIX からアンインストールするには、 Snap Creator サーバのインストールフォルダを削除します。 
---
= UNIX での Snap Creator サーバのアンインストール
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator サーバを UNIX からアンインストールするには、 Snap Creator サーバのインストールフォルダを削除します。

Snap Creator サーバのエンジンディレクトリ（ /install_path/scServer4.1.0/engine ）に、次のディレクトリおよび関連するすべてのサブディレクトリとファイルをバックアップします。

* Snap Creator データベース（ ./snapcreator ）
* Snap Creator サーバのプロパティ（ /etc ）
* 構成（ ./configs ）
* ログ（ ./logs ）
* プラグインリポジトリ（有効な場合）（ ./snapcreatorPlugin ）



NOTE: これらのディレクトリは必ずバックアップしてください。バックアップしておかないと、ユーザデータが失われてリカバリできなくなります。

Snap Creator サーバをアンインストールするには、次の手順を実行します。


NOTE: 以降の手順で示すパスは、汎用のインストールパスを参照してください。これらのコマンドのパスを変更して、カスタマイズした Snap Creator サーバのインストールパスを反映させることができます。

. 次のスクリプトを使用して、 Snap Creator サーバのサービス（「 napcreatorserverservice 」）を停止します。
+
[listing]
----
/install_path/scServer4.1.0/bin/scServer stop
----
. Snap Creator サーバのインストールフォルダを削除します。
+
たとえば、 Linux システムの場合は次のコマンドを実行します。

+
[listing]
----
rm -Rf /install_path/scServer4.1.0
----

