---
permalink: sap-hana-ops/concept_housekeeping_of_log_backups.html 
sidebar: sidebar 
keywords: housekeeping, log, backups 
summary: SAP HANA での不要なログバックアップの削除は、 HANA Studio の機能、または選択したバックアップよりも古いすべてのバックアップを削除できる SQL ステートメントに基づいています。 
---
= 不要なログバックアップの削除
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP HANA での不要なログバックアップの削除は、 HANA Studio の機能、または選択したバックアップよりも古いすべてのバックアップを削除できる SQL ステートメントに基づいています。

Snap Creator は、定義された保持ポリシーに基づいて、プライマリストレージまたはセカンダリストレージ上の Snapshot コピーを削除し、 HANA カタログ内の対応するエントリを削除することで、データバックアップ（ Snapshot コピー）の削除を処理します。

最新のデータバックアップよりも古いログバックアップは、不要なため削除されます。

Snap Creator は、ファイルシステムレベルおよび SAP HANA バックアップカタログ内での不要なログファイルバックアップの削除を処理します。Snap Creator を使用して各 Snapshot バックアップの一部として実行される処理は次のとおりです。

* バックアップカタログを読み取って、成功した最も古いデータまたは Snapshot バックアップのバックアップ ID を取得する。
* 最も古いバックアップよりも古いバックアップをすべて削除します。



NOTE: Snap Creator では、不要なバックアップは Snapshot コピーに基づいてのみ処理されます。追加のファイルベースのバックアップを作成する場合は、ファイルベースのバックアップがバックアップカタログとファイルシステムから削除されていることを確認する必要があります。このようなデータバックアップをバックアップカタログから手動で削除しないと、最も古いデータバックアップになる可能性があり、ログバックアップの不要ファイルの削除処理は失敗します。
