---
permalink: sap-hana-ops/concept_considerations_for_backing_up_sap_hana_systems.html 
sidebar: sidebar 
keywords: considerations, backup, backing, up, sap, hana 
summary: SAP HANA 管理者は、信頼性の高いレベルのサービスを提供し、バックアップによるダウンタイムやパフォーマンスの低下を最小限に抑える必要があります。 
---
= SAP HANA システムのバックアップに関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
SAP HANA 管理者は、信頼性の高いレベルのサービスを提供し、バックアップによるダウンタイムやパフォーマンスの低下を最小限に抑える必要があります。

このようなサービスレベルを実現するため、 SAP HANA 管理者は、次の分野の課題に対処します。

* 本番用 SAP システムのパフォーマンスへの影響
+
バックアップ中はデータベースサーバ、ストレージシステム、およびストレージネットワークに大きな負荷がかかるため、一般にバックアップは本番用 SAP システムのパフォーマンスに大きく影響します。

* バックアップウィンドウの短縮
+
バックアップは、 SAP システムで発生する I/O アクティビティやバッチアクティビティが少ない時間帯にしか作成できません。SAP システムが常時アクティブになっていると、バックアップウィンドウを定義することはきわめて困難です。

* データの急増
+
バックアップウィンドウが短くなる一方でデータは急増しているため、より多くのテープドライブ、新しいテープドライブテクノロジ、より速いストレージネットワークを求めて、バックアップインフラに投資し続けることになります。また、データベースが拡大すると、バックアップ用により多くのテープメディアやディスクスペースが必要になります。こうした問題には差分バックアップで対処することもできますが、リストアプロセスが非常に遅くなるため、一般には受け入れられません。

* ダウンタイムのコスト増
+
SAP システムの計画外停止は、例外なくコストに影響します。計画外停止の大部分を占めるのは、障害発生時に必要となる SAP システムのリストアとリカバリの時間です。バックアップとリカバリのアーキテクチャを設計するときは、許容される Recovery Time Objective （ RTO ；目標復旧時間）に応じて設計する必要があります。

* バックアップとリカバリの時間
+
バックアップとリカバリの時間は、 SAP アップグレードプロジェクトに含まれています。SAP アップグレードのプロジェクト計画には、 SAP データベースのバックアップが必ず 3 つ以上含まれます。これらのバックアップに要する時間により、アップグレードプロセスに要する合計時間が短縮されます。一般に、バックアップとリカバリは、以前に作成したバックアップからデータベースをリストアおよびリカバリするのに要する時間に基づいて行われます。リストアを短時間で実行すれば、システムを以前の状態に戻すだけでなく、アップグレード中に発生する可能性がある問題を解決するための時間を短縮できます。


