---
permalink: sap-hana-ops/reference_troubleshooting.html 
sidebar: sidebar 
keywords: troubleshooting 
summary: トラブルシューティングのセクションでは、エラーコード、エラーメッセージに関する情報を提供し、問題を解決するための概要または解決策を紹介します。 
---
= トラブルシューティング
:icons: font
:imagesdir: ../media/


[role="lead"]
トラブルシューティングのセクションでは、エラーコード、エラーメッセージに関する情報を提供し、問題を解決するための概要または解決策を紹介します。

次の表に、 SAP HANA プラグインのエラーメッセージを示します。

|===
| エラーコード | エラーメッセージです | 説明 / 解決策 


 a| 
hdb-00001
 a| 
指定された設定パラメータを使用して hdbsql コマンドを実行するためのアクセス可能な HANA ノードが見つかりません。構成の HANA 設定を確認して更新し、再試行してください。
 a| 
HANA ノードが実行中で到達可能であり、指定されたインスタンス番号が正しいことを確認します。



 a| 
hdb-00002
 a| 
[$sid] のデータベース Snapshot の作成に失敗しました。
 a| 
HANA データベースの Snapshot がデータベースにすでに作成されているかどうかを確認します。HANA データベースの Snapshot がすでに作成されている場合は、削除するか、休止解除処理を実行します。ログで他のエラーメッセージや詳細を確認して、まだ作成していない場合は確認します。



 a| 
hdb-00003
 a| 
[$sid] のデータベース Snapshot の削除に失敗しました。
 a| 
HANA データベースの Snapshot がすでに削除されているかどうかを確認します。「はい」の場合、このエラーは無視してかまいません。「いいえ」の場合は、 SAP HANA プラグインのパラメータを確認し、ノードにアクセスできること、および指定したインスタンス番号が正しいことを確認します。



 a| 
hdb-00004
 a| 
接続が拒否されたため、インスタンス [$instance] を持つ [$hana_node] ノードへの接続に失敗しました。
 a| 
メッセージにインスタンスが表示されている HANA ノードにアクセスできません。プラグインが他のノード上で hdbsql コマンドを実行しようとするので、これは単なる警告になります。ログをチェックして処理が成功したかどうかを確認してください。



 a| 
hdb-00005
 a| 
データベース [$sid] にはすでに Snapshot があります。
 a| 
HANA データベースの Snapshot はデータベースにすでに存在します。この問題を解決するには、 HANA データベースの Snapshot を削除するか、休止解除処理を実行します。



 a| 
hdb-00006
 a| 
ホスト名 [$hana_node] を解決できません。
 a| 
HANA ノードのホスト名を解決できません。DNS サーバまたは etc hosts エントリを確認してください。



 a| 
hdb-00007
 a| 
ユーザ名またはパスワードが無効です。クレデンシャルを確認して再試行してください。
 a| 
HANA データベースに対して指定されたユーザ名とパスワードが正しくありません。構成ファイルのエントリを修正してから再試行してください。



 a| 
hdb-00008
 a| 
[$hba_node] に対するコマンド [$hdbsql_cmd] の実行に失敗しました。
 a| 
プラグインが、設定で指定されたすべての HANA ノードで hdbsql コマンドを実行できませんでした。HANA のノードとインスタンスのパラメータを確認し、少なくとも 1 つの HANA ノードが起動していてアクセス可能であることを確認してください。



 a| 
hdb-00009
 a| 
HANA [$info] が見つかりません。
 a| 
SAP HANA Plug-in SCDUMP 処理で、 HANA データベースから特定の情報を取得できませんでした。HANA のノードとインスタンスのパラメータを確認し、少なくとも 1 つの HANA ノードが起動していてアクセス可能であることを確認します。



 a| 
hdb-00010
 a| 
OS 情報の収集に失敗しました。
 a| 
Windows 環境で OS 情報の収集が失敗しました。 Windows では SAP HANA プラグインがサポートされていません。代わりに SLES オペレーティングシステムを使用してください。



 a| 
hdb-00011
 a| 
OS 情報の収集に失敗しました。
 a| 
Snap Creator が SCDUMP 処理の OS 情報を収集できませんでした。エージェント設定ファイルを確認して、設定を修正してください。



 a| 
hdb-00012
 a| 
SnapDrive 情報の収集に失敗しました。
 a| 
SAP HANA プラグインは、 NFS 環境でのみサポートされます。HANA データベースの構成で SnapDrive が有効になっています。構成ファイルで snapdrive = n を設定します。



 a| 
hdb-00013
 a| 
hana_nodes パラメータは設定されていません。構成ファイルで HANA の設定を確認します。
 a| 
SAP HANA プラグインには、 HANA nodes （ hana_nodes ）パラメータを指定する必要があります。パラメータを設定してやり直してください。



 a| 
hdb-00014
 a| 
指定された構成パラメータを使用して hdbsqlコマンド を実行するためのアクセス可能な HANA ノードが見つかりません。構成の HANA 設定を確認して更新し、再試行してください。
 a| 
HANA ノードが実行中で到達可能であり、指定されたインスタンス番号が正しいことを確認します。



 a| 
hdb-00015
 a| 
hana_instance パラメータが設定されていません。構成ファイルで HANA の設定を確認します。
 a| 
SAP HANA プラグインには HANA インスタンス（ hana_instance ）パラメータが必要です。パラメータを設定してやり直してください。



 a| 
hdb-00016
 a| 
hana_password パラメータが設定されていません。構成ファイルで HANA の設定を確認します。
 a| 
SAP HANA プラグインには、 HANA パスワード（ hana_password ）パラメータが必要です。パラメータを設定してやり直してください。



 a| 
hdb-00017
 a| 
hdbsql へのパス。パラメータ HA_HDBSQL _CMD の値が無効です。
 a| 
次のいずれかが発生しました：

* hdbsql パスが指定されていません
* 指定された hdbsql パスが正しくありません。


Snap Creator エージェントがインストールされている管理ホストに HANA hdbsql クライアントがインストールされていることを確認し、 HANA パラメータに hdbsql バイナリの正しいパスを指定してから、再試行してください。

|===