---
permalink: domino-ops/concept_restore_operations_using_domino_plug_in.html 
sidebar: sidebar 
keywords: domino, ibm, understanding, plug-in, restore 
summary: IBM Domino プラグインは、データベースが格納されているボリュームの Snapshot コピーからデータベースファイルをリストアします。Snapshot のリストア処理が完了すると、 changeinfo ディレクトリに記録された変更がプラグインによって適用されます。 
---
= IBM Domino プラグインのリストア処理の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM Domino プラグインは、データベースが格納されているボリュームの Snapshot コピーからデータベースファイルをリストアします。Snapshot のリストア処理が完了すると、 changeinfo ディレクトリに記録された変更がプラグインによって適用されます。

大まかな手順は次のとおりです。

. Snapshot コピーからデータベースファイルをリストアします。
. changeinfo ディレクトリに記録された変更を適用します
. トランザクションログ情報がある場合は適用します。




== リストアオプション

このプラグインには、さまざまなリストア・オプションが用意されています。

|===


| リストアタイプ | 説明 


 a| 
ボリュームリストア（ポイントインタイム）
 a| 
ボリューム全体を Snapshot コピー時点の状態にリストアします。



 a| 
ボリュームリストア（最新の状態）
 a| 
ボリューム全体を Snapshot コピー時点の状態にリストアし、 Domino トランザクションログを最新のコピーに対して再生します。



 a| 
ボリュームリストア（選択可能な最新の状態へ）
 a| 
Snapshot コピー時点の状態にボリューム全体をリストアし、指定時刻に対する Domino トランザクションログを再生します。



 a| 
単一ファイルのリストア（ポイントインタイム）
 a| 
Snapshot コピー作成時の状態に単一のファイルをリストアします（ NFS のみ）。



 a| 
単一ファイルのリストア（最新の状態）
 a| 
Snapshot コピー時点の状態に単一のファイルをリストアし、最新のコピーに対する Domino トランザクションログを再生します（ NFS のみ）。



 a| 
単一ファイルのリストア（選択可能な最新の状態へ）
 a| 
Snapshot コピー時点の状態に単一のファイルをリストアし、指定時刻に対する Domino トランザクションログを再生します（ NFS のみ）。

|===
* 注：最新の状態へのリストアおよび選択可能な最新の状態へのリストアの場合、 Domino トランザクションログを有効にする必要があります。

トランザクションログは、フォワード再生のみ可能です。Snapshot コピーが作成されるまでの時間を選択するとリストアエラーが発生します。
