---
permalink: domino-ops/concept_backup_operations_using_domino_plug_in.html 
sidebar: sidebar 
keywords: domino, ibm, backup, operations, ibm, understanding 
summary: 他のバックアップテクノロジとは異なり、 IBM Domino プラグインでは、バックアップ処理中にデータベースにデータを書き込むことができます。バックアップ処理中に、 changeinfo という一時ディレクトリにデータベースへの変更を記録することにより、バックアップとアプリケーションデータの整合性を確保します。リストア時に、 Snapshot コピーからデータをリストアしたあと、それらの変更がデータベースに適用されます。 
---
= IBM Domino プラグインのバックアップ処理の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
他のバックアップテクノロジとは異なり、 IBM Domino プラグインでは、バックアップ処理中にデータベースにデータを書き込むことができます。バックアップ処理中に、 changeinfo という一時ディレクトリにデータベースへの変更を記録することにより、バックアップとアプリケーションデータの整合性を確保します。リストア時に、 Snapshot コピーからデータをリストアしたあと、それらの変更がデータベースに適用されます。

バックアップ処理中は、データベースファイルはバックアップモードと呼ばれます。Snap Creator Framework はこれらのファイルを「 Quiesced 」と呼びますが、これは当てはまりません。Snapshot コピーの作成中も、ファイルへのデータの書き込みは継続されます。

大まかな手順は次のとおりです。

. バックアップするボリューム内のデータベース、テンプレート、およびメールボックスをリスト表示します。
. ファイルをバックアップモードにします。一度に 1 つのデータベースが必要です。
. データベースに整合性がないか、破損していないかを
+

NOTE: 手順で説明したように、エラーが発生してもプラグインを強制的にバックアップ処理を続行できます link:task_using_the_gui_to_create_a_configuration_file.md#STEP_AA41331683A24598B7845367CB967F99["task_using_or_GUI_To_create_a_configuration-file.md#step_AA41331683A24598B7845367CB967F99"]。

. 各ボリュームの Snapshot コピーを作成します。
. Domino トランザクションログを使用している場合、最新の状態へのリストア処理で使用する Domino トランザクションログのアーカイブコピーを作成します。
. ファイルのバックアップモードを解除します。一度に 1 つのデータベースが必要です。
. ファイルがバックアップモードになって changeinfo ディレクトリに格納されたため、データベースへの変更を記録します。

