---
permalink: domino-ops/reference_storage_layout_requirements.html 
sidebar: sidebar 
keywords: domino, ibm, storage, layout, requirements, 
summary: 一般的な IBM Domino 環境には、 Domino データ用に 1 つ、 Domino トランザクションログ用に 1 つ、プラグインの changeinfo ディレクトリ用に 1 つ以上の Domino ボリュームがあります。多くのサイトには、 Domino DAOS 用のボリュームとビューの再構築用のボリュームがあります。 
---
= ストレージレイアウトの要件
:icons: font
:imagesdir: ../media/


[role="lead"]
一般的な IBM Domino 環境には、 Domino データ用に 1 つ、 Domino トランザクションログ用に 1 つ、プラグインの changeinfo ディレクトリ用に 1 つ以上の Domino ボリュームがあります。多くのサイトには、 Domino DAOS 用のボリュームとビューの再構築用のボリュームがあります。

IBM Domino プラグインは、バックアップ処理中に記録された変更および最新の状態へのリストア処理で使用されるトランザクションログのコピーに changeinfo ディレクトリを使用します。changeinfo ディレクトリは別のボリュームに保存し、誤って情報を上書きしてバックアップを容易にすることを推奨します。

また、 Domino DAOS （有効になっている場合）とビューの再構築用に別々のボリュームを用意しておくと便利です。Domino がビューを再構築すると（たとえば、インデックスが削除されたビューをユーザが開いたときや updall -- R が実行されたときなど）、一時ファイルが生成され、高速ビュー再構築のためにデータがソートされることがあります。

デフォルトでは、これらの一時ファイルはシステムの一時フォルダまたは Domino データフォルダに格納されます。IBM では、一時ファイルの場所を別のドライブに変更して、ディスク I/O を分散し、ビューを再構築するための十分な領域を確保することを推奨しています。ビューの再構築に使用する一時フォルダを変更するには 'View_Rebuild_Dir 設定を notes.ini ファイルに追加します

次の表に、推奨されるボリュームレイアウトを示します。

|===
| ボリューム | 内容 | 注： 


 a| 
ボリューム 1
 a| 
Domino データ
 a| 
FC 、 SAS 、または SSD ドライブが優先されます。



 a| 
ボリューム 2
 a| 
Domino トランザクションログ
 a| 
FC 、 SAS 、または SSD ドライブが優先されます。



 a| 
ボリューム 3
 a| 
変更情報
 a| 
バックアップ処理中に記録された変更および最新の状態へのリストア処理で使用するトランザクションログのコピーを格納します。



 a| 
ボリューム 4
 a| 
再構築を表示します
 a| 
任意。インデックスの更新中に作成された一時ファイルを格納します。RAM ディスクを使用可能。View_Rebuild_Dir 設定を notes.ini ファイルに追加します。



 a| 
ボリューム 5
 a| 
DAOS リポジトリ
 a| 
任意。DAOS の .do ファイルが含まれています。I/O 要件が低いため、 SATA ドライブに適しています。

|===

NOTE: 仮想環境では、ゲストでマウントされたディスクが推奨されます。
