---
permalink: domino-ops/task_performing_point_in_time_volume_restore.html 
sidebar: sidebar 
keywords: domino, ibm, volume, restore 
summary: IBM Domino プラグインを使用して、主要なすべてのストレージタイプについて、ポイントインタイム、最新の状態へのリストア、または選択可能な最新の状態へのボリュームのリストアを実行できます。 
---
= ボリュームリストアを実行しています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM Domino プラグインを使用して、主要なすべてのストレージタイプについて、ポイントインタイム、最新の状態へのリストア、または選択可能な最新の状態へのボリュームのリストアを実行できます。

次の点を確認してください。

* 構成ファイルで、データリストアディレクトリを Domino データディレクトリに設定します。
* Domino サーバを停止します。


ボリュームリストアオプションは次のとおりです。

|===
| リストアタイプ | 説明 


 a| 
ボリュームリストア（ポイントインタイム）
 a| 
ボリューム全体を Snapshot コピー時点の状態にリストアします。



 a| 
ボリュームリストア（最新の状態）
 a| 
ボリューム全体を Snapshot コピー時点の状態にリストアし、 Domino トランザクションログを最新のコピーに対して再生します。



 a| 
ボリュームリストア（選択可能な最新の状態へ）
 a| 
Snapshot コピー時点の状態にボリューム全体をリストアし、指定時刻に対する Domino トランザクションログを再生します。

|===

NOTE: 最新の状態へのリストアおよび選択可能なポイントインタイムリストアの場合、 Domino トランザクションログを有効にする必要があります。

トランザクションログは、フォワード再生のみ可能です。Snapshot コピーが作成されるまでの時間を選択するとリストアエラーが発生します。

. [ プロファイルと構成 ] ペインで構成ファイルを選択し、 [* アクション *>* リストア *] をクリックします。
+
「 * Restore * 」を選択すると、 Snap Creator Framework のリストアウィザードが自動的に起動します。リストアウィザードの実行中に、 [ 次へ ] をクリックして次のページに進みます。前のページに戻るには、「戻る」をクリックします。

+

NOTE: SnapVault コピーからリストアする場合は、プライマリストレージまたはセカンダリストレージからリストアするように求められます。選択する項目は、で説明する制限の処理方法によって異なります link:concept_domino_database_restore_overview.html["データベースのリストア"]。

. リストアの詳細ページで、リストアの詳細を指定します。
+
|===
| フィールド | 手順 


 a| 
Controller/Vserver 名
 a| 
リストア元となるストレージシステム上の SVM を選択します。



 a| 
ボリューム名を復元します
 a| 
リストア元のボリュームを選択します。



 a| 
ポリシー
 a| 
リストア元のバックアップのポリシーを選択します。



 a| 
Snap Creator の Snapshot コピー / すべての Snapshot コピー
 a| 
デフォルトのままにします。



 a| 
リストア Snapshot コピーの名前
 a| 
リストア元の Snapshot コピーを選択します。



 a| 
リストアタイプ
 a| 
「 * Volume Restore （ボリューム復元）」を選択します

|===
. 次のページで、ボリュームのリストアタイプを指定します。
+
|===
| フィールド | 手順 


 a| 
リストアタイプ
 a| 
ボリュームのリストアタイプをクリックします。[ 選択可能な最新の状態 * ] を選択した場合、新しいフィールドが表示され、 Domino トランザクションログの再生日時を指定できます。Snap Creator サーバの時間がストレージコントローラの時間と一致しない場合は、 * Ignore Validation * をクリックします。



 a| 
レプリケーションを無効にします
 a| 
リストアされたデータベースファイルに新しい Domino レプリカ ID を設定するには、このボックスを選択します。

|===
. 概要を確認し、 [ 完了 ] をクリックします。
. [ ボリュームの復元 ] ダイアログで、 [OK] をクリックします。
+
Snap Creator がリストアジョブを開始します。ジョブ情報がコンソールペインに表示されます。



リストア処理が完了したら、 Domino サーバを再起動します。
