---
permalink: domino-ops/task_setting_the_snap_creator_archive_log_management_settings.html 
sidebar: sidebar 
keywords: domino, ibm, cleaning up, purging, archives, archived, copies, transaction, logs 
summary: Domino トランザクションログを使用している場合、 IBM Domino プラグインは、最新の状態へのリストア処理で使用するために、 Domino トランザクションログのコピーを changeinfo ディレクトリにアーカイブします。Snap Creator が不要になったトランザクションログのコピーをクリーンアップするには、トランザクションログの管理を有効にする必要があります。 
---
= Domino トランザクションログのアーカイブコピーをクリーンアップしています
:icons: font
:imagesdir: ../media/


[role="lead"]
Domino トランザクションログを使用している場合、 IBM Domino プラグインは、最新の状態へのリストア処理で使用するために、 Domino トランザクションログのコピーを changeinfo ディレクトリにアーカイブします。Snap Creator が不要になったトランザクションログのコピーをクリーンアップするには、トランザクションログの管理を有効にする必要があります。

Domino プラグインは、 changeinfo ファイルおよび changeinfo ディレクトリに Domino トランザクションログのアーカイブコピーを格納します。プラグインは、設定の保持ポリシーに基づいて、 .info ファイルを自動的にクリーンアップします。Snap Creator でトランザクションログ管理を明示的に有効にしないかぎり、トランザクションログの不要なコピーはクリーンアップされません。

トランザクションログ管理のセットアップで、最新の状態へのリストア処理用に保持するトランザクションログのアーカイブコピー数と、 changeinfo ディレクトリを含むボリュームサイズとの間に、適切なバランスを取るようにします。


IMPORTANT: Archive Log ディレクトリのパラメータを、 Domino トランザクションログのパスに設定しないでください。これを行うと、 Domino 環境が破損する可能性があります。

. [ プロファイルと構成 ] ペインで構成ファイルを選択し、 [ * アーカイブログの管理 * ] タブをクリックします。
. [ * アーカイブ・ログ管理 * ] タブで、トランザクション・ログ管理設定に次の値を指定します。
+
|===
| パラメータ | 設定 | 説明 


 a| 
アーカイブログを有効にします
 a| 
Y
 a| 
トランザクションログのクリーンアップを有効にします。



 a| 
アーカイブログの保持
 a| 
Snapshot コピーを保持する日数以上の値を入力してください。
 a| 
トランザクションログを保持する日数。



 a| 
アーカイブログディレクトリ
 a| 
changeinfo/logs
 a| 
クリーンアップするディレクトリ。* 重要： * Domino トランザクションログのパスを指定しないでください。これを行うと、 Domino 環境が破損する可能性があります。



 a| 
アーカイブログの拡張機能
 a| 
 a| 
Domino トランザクションログファイルのコピーの拡張子。



 a| 
アーカイブログ再帰検索
 a| 
N
 a| 
Snap Creator プラグインは、 changeinfo ディレクトリの logs サブディレクトリに .txt ファイルを格納するため、再帰的な検索は必要ありません。

|===
. [ 構成コンテンツ ] ペインで [ 保存 ] をクリックして、変更を保存します。

