---
permalink: domino-ops/task_performing_point_in_time_single_file_restore_with_nfs.html 
sidebar: sidebar 
keywords: snap creator, ibm, domino, plug-in, perfomring, single-file, single, file restore 
summary: IBM Domino プラグインを使用して、 NFS 環境のデータベースに対して、ポイントインタイムリストア、最新の状態へのリストア、または選択可能な最新の状態への単一ファイルのリストアを実行できます。 
---
= 単一ファイルのリストアを実行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM Domino プラグインを使用して、 NFS 環境のデータベースに対して、ポイントインタイムリストア、最新の状態へのリストア、または選択可能な最新の状態への単一ファイルのリストアを実行できます。

構成ファイルの Data Restore DirectoryParameter を、 Domino データボリュームの正しいサブディレクトリに設定する必要があります。


NOTE: 単一ファイルのリストアのために Domino サーバを停止する必要はありません。

単一ファイルのリストアオプションは次のとおりです。

|===
| リストアタイプ | 説明 


 a| 
単一ファイルのリストア（ポイントインタイム）
 a| 
Snapshot コピー作成時の状態に単一のファイルをリストアします（ NFS のみ）。



 a| 
単一ファイルのリストア（最新の状態）
 a| 
Snapshot コピー時点の状態に単一のファイルをリストアし、最新のコピーに対する Domino トランザクションログを再生します（ NFS のみ）。



 a| 
単一ファイルのリストア（選択可能な最新の状態へ）
 a| 
Snapshot コピー時点の状態に単一のファイルをリストアし、指定時刻に対する Domino トランザクションログを再生します（ NFS のみ）。

|===

NOTE: 最新の状態へのリストアおよび選択可能なポイントインタイムリストアの場合、 Domino トランザクションログを有効にする必要があります。

トランザクションログは、フォワード再生のみ可能です。Snapshot コピーが作成されるまでの時間を選択するとリストアエラーが発生します。

. [ プロファイルと構成 ] ペインで構成ファイルを選択し、 [* アクション *>* リストア *] をクリックします。
+
「 * Restore * 」を選択すると、 Snap Creator Framework のリストアウィザードが自動的に起動します。リストアウィザードの実行中は、 [ 次へ ] をクリックして次のページに進み、 [ 戻る ] をクリックして前のページに戻ります。

+

NOTE: SnapVault コピーからリストアする場合は、プライマリストレージまたはセカンダリストレージからリストアするように求められます。選択する項目は、で説明する制限の処理方法によって異なります link:concept_domino_database_restore_overview.md#GUID-4D864E27-DE54-43BF-9B9F-EF2F240F65D9["concept_DOMINO_DATABASE_RESTORE_overview.md#GUID-4D864E27-DE54-43BF-9B9F-EF2F240F65D9"]。

. リストアの詳細ページで、リストアの詳細を指定します。
+
|===
| フィールド | 手順 


 a| 
Controller/Vserver 名
 a| 
リストア元となるストレージシステム上の SVM を選択します。



 a| 
ボリューム名を復元します
 a| 
リストア元のボリュームを選択します。



 a| 
ポリシー
 a| 
リストア元のバックアップのポリシーを選択します。



 a| 
Snap Creator の Snapshot コピー / すべての Snapshot コピー
 a| 
デフォルトのままにします。



 a| 
リストア Snapshot コピーの名前
 a| 
リストア元の Snapshot コピーを選択します。



 a| 
リストアタイプ
 a| 
[ 単一ファイルの復元 *] を選択します。

|===
. 次のページで、リストアするファイルを選択します。
+
ファイルは、そのフルパス名とともに、 [ * ソースパス * （ * Source path * ） ] フィールドに表示されます。

+

TIP: パス名をクリップボードにコピーしてあとで使用できるようにします。

. 次のページで、ファイルのリストア先となるディレクトリを選択します。
+
ファイルの親サブディレクトリの名前は、ソースパスの親サブディレクトリの名前と同じである必要があります。たとえば、ソースパスが /DOMINO_/data/mail/user2.nsf の場合、リストアパスは /DOMINO_/data/restore/mail/user2.nsf です。

+
ディレクトリの完全パス名が * Destination path * フィールドに表示されます。

. 次のページで、単一ファイルのリストアタイプを指定します。
+
|===
| フィールド | 手順 


 a| 
リストアタイプ
 a| 
単一ファイルのリストアタイプをクリックします。[ 選択可能な最新の状態 * ] を選択した場合、新しいフィールドが表示され、 Domino トランザクションログの再生日時を指定できます。Snap Creator サーバの時間がストレージコントローラの時間と一致しない場合は、 * Ignore Validation * をクリックします。



 a| 
レプリケーションを無効にします
 a| 
リストアされたデータベースファイルに新しい Domino レプリカ ID を設定するには、このボックスを選択します。

|===
. 概要を確認し、 [ 完了 ] をクリックします。
. [ 単一ファイルの復元 ] ダイアログで、 [OK] をクリックします。
+
Snap Creator がリストアジョブを開始します。ジョブ情報がコンソールペインに表示されます。


